/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/geometry/contour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Contour
         * @description 保存母线：归一化为 canonical JSON 落盘 ``data/contours/<id>.json``。
         *
         *     落盘内容就是 canonical JSON 本体（不含包装元数据），因此
         *     "读取 → 再规范化" 必须与原文件**逐字节相同**——这正是往返一致的判据。
         */
        post: operations["save_contour_api_geometry_contour_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/contour/{contour_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Contour
         * @description 载入母线。文件不存在时返回 404（由 :class:`ArtifactNotFoundError` 映射）。
         */
        get: operations["load_contour_api_geometry_contour__contour_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Profile
         * @description 母线层校验（纯 Python，无内核）：几何自洽 + G1 + 尖点 + 设计意图断言。
         *
         *     响应**同时返回分段采样点**（``sample`` / ``outline``），供前端 2D 剖面与示意通道消费。
         *     这是 ADR-011 的落实方式：端点数值全部来自后端，前端不做任何几何计算。
         */
        post: operations["validate_profile_api_geometry_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Geometry
         * @description 构建回转几何：**命中即同步返回**，未命中建异步作业（规格 §9.3）。
         */
        post: operations["build_geometry_api_geometry_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description 查询作业快照。作业不存在时返回 404。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{key}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description 返回产物文件；不在白名单或文件缺失时 404。
         */
        get: operations["get_artifact_api_artifacts__key___file__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provenance/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provenance
         * @description 返回产物清单（provenance.json 内容），供溯源与排障（§9.2 / R-14）。
         */
        get: operations["get_provenance_api_provenance__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针。
         *
         *     M0 验收项（规格 §16）：必须返回版本号，供前端与 CI 核对后端已就绪。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArcSegment
         * @description 球冠段（圆弧）：半径端半径 R 与轴向跨度 H 唯一确定球半径 ρ=(R²+H²)/2H。
         */
        ArcSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "arc";
        };
        /**
         * BuildResponse
         * @description ``POST /api/geometry/build`` 的响应体（§9.3 缓存优先）。
         */
        BuildResponse: {
            /**
             * Cache Hit
             * @description True 表示产物已存在，metrics 直接可用，未创建作业
             */
            cache_hit: boolean;
            /**
             * Key
             * @description 内容寻址缓存键（sha256 十六进制）
             */
            key: string;
            /**
             * Job Id
             * @description 未命中时返回；用 /ws/jobs/{job_id} 订阅进度
             */
            job_id?: string | null;
            /**
             * Metrics
             * @description 命中时的产物指标
             */
            metrics?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CheckResult
         * @description 单项检查结果。
         */
        CheckResult: {
            /**
             * Check
             * @description 检查项名称
             */
            check: string;
            /**
             * Severity
             * @description 裁定：pass / warn / fail / skip
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
            /**
             * Detail
             * @description 人类可读的说明
             */
            detail: string;
            /**
             * Value
             * @description 实测值
             */
            value?: number | null;
            /**
             * Expected
             * @description 期望值
             */
            expected?: number | null;
            /**
             * Relative Error
             * @description 相对误差
             */
            relative_error?: number | null;
        };
        /**
         * ContourResponse
         * @description 母线响应体。``canonical`` 即落盘内容，往返一致的判据（规格 §16.3）。
         */
        ContourResponse: {
            /** Id */
            id: string;
            /**
             * Canonical
             * @description canonical JSON：键序固定、浮点定量、无多余空白
             */
            canonical: string;
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * ContourSaveRequest
         * @description 保存母线的请求体。
         */
        ContourSaveRequest: {
            /**
             * Id
             * @description 母线标识；省略时按 name 派生或随机生成
             */
            id?: string | null;
            /** @description 母线剖面（段链，单位米） */
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * EllipseSegment
         * @description 椭圆弧段：半轴 = (半径端半径 R, 轴向跨度 H)，椭圆心在轴线上。
         */
        EllipseSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ellipse";
        };
        /**
         * ErrorBody
         * @description §10.3 规定的错误响应体。
         */
        ErrorBody: {
            /**
             * Code
             * @description 机器可读的错误码，如 GEOMETRY_G1_DISCONTINUITY
             */
            code: string;
            /**
             * Stage
             * @description 发生阶段：params / meridian / solid / mesh / step / …
             */
            stage: string;
            /**
             * Message
             * @description 面向用户的中文说明
             */
            message: string;
            /**
             * Details
             * @description 结构化上下文
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Suggestion
             * @description 可操作的修复建议（规格 §10.3 要求必填）
             */
            suggestion: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/health`` 的响应体。
         *
         *     作为 OpenAPI schema 的来源，前端 TS 类型由此生成（规格 §18.2：禁止手写重复类型）。
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * JobRecord
         * @description 作业状态快照（跨线程传递的**纯数据**，不含任何几何对象）。
         */
        JobRecord: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** @default queued */
            stage: components["schemas"]["JobStage"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Result Key */
            result_key?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
        };
        /**
         * JobStage
         * @description §9.3 的进度阶段（M1 子集：几何链 ``meridian → solid → mesh → step → done``）。
         * @enum {string}
         */
        JobStage: "queued" | "meridian" | "solid" | "mesh" | "step" | "done";
        /**
         * JobStatus
         * @description §9.3 的作业生命周期状态。
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JointCheck
         * @description 段间接头（G0 由结构保证，此处校 G1）。
         */
        JointCheck: {
            /**
             * Index
             * @description 接头序号：段 index 与 index+1 之间
             */
            index: number;
            /** Z */
            z: number;
            /** Radius */
            radius: number;
            /**
             * Angle Deg
             * @description 两侧切向夹角（度）
             */
            angle_deg: number;
            /**
             * Kind
             * @description g1 = 常规切向；pinch = 轴处反向尖点
             * @enum {string}
             */
            kind: "g1" | "pinch";
            /**
             * Severity
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
        };
        /**
         * LineSegment
         * @description 直线段：柱段（end_radius == 起点半径）或锥段/锥台。
         */
        LineSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "line";
        };
        /**
         * MeridianProfile
         * @description 母线剖面：底部半径 + 自下而上的段链（规格 §5.2）。
         *
         *     剖面在 (r, z) 平面内描述，回转轴为 Z 轴，单位米。
         *     实体 = 区域 ``{(r, z)}`` 绕 Z 轴回转 360°，其中区域由
         *     ``(0,0) → (base_radius,0) → [段链] → (r_end,z_end) → (0,z_end) → (0,0)`` 围成。
         */
        MeridianProfile: {
            /**
             * Name
             * @description 剖面名称（仅用于展示，不参与几何）
             * @default
             */
            name: string;
            /**
             * Base Radius
             * @description z=0 处的半径（m）
             */
            base_radius: number;
            /**
             * Segments
             * @description 自下而上的段链
             */
            segments: (components["schemas"]["LineSegment"] | components["schemas"]["ArcSegment"] | components["schemas"]["EllipseSegment"])[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationReport
         * @description 母线层校验报告（同步接口返回体）。
         */
        ValidationReport: {
            /** Ok */
            ok: boolean;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Joints */
            joints: components["schemas"]["JointCheck"][];
            /**
             * Sample
             * @description 剖面采样点 (r, z)，米
             */
            sample: [
                number,
                number
            ][];
            /**
             * Outline
             * @description 闭合轮廓 (r, z)，米
             */
            outline: [
                number,
                number
            ][];
            /**
             * Envelope
             * @description 解析包络 (2R, 2R, L)，米
             */
            envelope: [
                number,
                number,
                number
            ];
            /**
             * Volume
             * @description 解析体积（m³）
             */
            volume: number;
            /** Surface Area */
            surface_area: number;
            /** Centroid Z */
            centroid_z: number;
            /** Max Radius */
            max_radius: number;
            /** Total Length */
            total_length: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_contour_api_geometry_contour_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContourSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_contour_api_geometry_contour__contour_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 母线标识 */
                contour_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_profile_api_geometry_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_geometry_api_geometry_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__key___file__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_api_provenance__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
