/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/geometry/contour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Contour
         * @description 保存母线：归一化为 canonical JSON 落盘 ``data/contours/<id>.json``。
         *
         *     落盘内容就是 canonical JSON 本体（不含包装元数据），因此
         *     "读取 → 再规范化" 必须与原文件**逐字节相同**——这正是往返一致的判据。
         */
        post: operations["save_contour_api_geometry_contour_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/contour/{contour_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Contour
         * @description 载入母线。文件不存在时返回 404（由 :class:`ArtifactNotFoundError` 映射）。
         */
        get: operations["load_contour_api_geometry_contour__contour_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Profile
         * @description 母线层校验（纯 Python，无内核）：几何自洽 + G1 + 尖点 + 设计意图断言。
         *
         *     响应**同时返回分段采样点**（``sample`` / ``outline``），供前端 2D 剖面与示意通道消费。
         *     这是 ADR-011 的落实方式：端点数值全部来自后端，前端不做任何几何计算。
         */
        post: operations["validate_profile_api_geometry_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Geometry
         * @description 构建回转几何：**命中即同步返回**，未命中建异步作业（规格 §9.3）。
         *
         *     请求体兼容两种形态：裸剖面（既有契约）或 ``{"profile", "boosters"}``
         *     捆绑构型（OI-36）。键计算按同一份剖面对 boosters 敏感、对省略 boosters
         *     逐字节不敏感（§9.2）。
         */
        post: operations["build_geometry_api_geometry_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description 跑 §6.3 约束 + §6.5 诊断规则集。
         *
         *     结构错误（缺字段 / 类型不符 / 超出枚举）在进入本函数之前就被 pydantic 拦下，
         *     由 ``main`` 的 ``RequestValidationError`` 处理器翻成同一形状的六字段裁定。
         */
        post: operations["diagnose_api_params_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Units
         * @description 下发 §6.4 的显示单位全表。
         *
         *     这是**只读呈现口径**：不改变存储 / 计算 / 缓存键，故调整显示单位**不得**使
         *     ``artifacts/`` 缓存失效（§9.2）。
         */
        get: operations["units_api_params_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Thresholds
         * @description 返回阈值的生效值与来源。
         *
         *     刻意返回**生效值**而不是"文件里的值"：``PUT`` 之后环境变量仍然覆盖 ``config.toml``，
         *     若界面显示的是文件内容，用户会看到一个"保存了却不生效"的数字而找不到原因。
         */
        get: operations["read_thresholds_api_params_thresholds_get"];
        /**
         * Write Thresholds
         * @description 把补丁写进 ``config.toml``，然后返回**重新读出的**生效状态。
         *
         *     请求体是扁平的 ``{键: 值}``；值为 ``null`` 即**清空该键**（回到「未配置」，
         *     对最小工艺厚度而言就是回到"不判定"）。键必须是 §6.5 已声明的阈值——
         *     多一个键即 422，而不是静默忽略（忽略会让用户以为保存成功）。
         */
        put: operations["write_thresholds_api_params_thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Template
         * @description 返回界面可编辑的示例骨架（§1.7.3 OI-32 的前置）。
         *
         *     ⚠ 这**不是** OI-29 的内置示例模板——模板库须逐条核对公开来源，归 M3。
         *     本端点只提供一份标注为「未经来源核对」的骨架，使参数面板不必自建一份
         *     "看起来像真的"的数字（那会形成与 §13.2 基准表冲突的第二套数字，违反 P1）。
         */
        get: operations["read_template_api_params_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description 下发内置模板清单（仅元数据；完整参数按 id 取详情）。
         */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match Template By Name
         * @description OI-34 名称匹配。
         *
         *     ⚠ 本路由**必须注册在** ``/{template_id}`` 之前：路由按注册顺序匹配，
         *     顺序颠倒会让 ``match`` 被当成模板 id 吞掉。
         */
        get: operations["match_template_by_name_api_templates_match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Template By Id
         * @description 下发一个模板的完整参数（含逐字段出处表）。
         */
        get: operations["read_template_by_id_api_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Materials
         * @description 材料库全量查询（含派生比强度 / 比刚度计算值）。
         */
        get: operations["list_materials_api_catalog_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Engine Catalog
         * @description 发动机族谱（§7.4）：缺省返回族清单 + 计数；给 ``family`` 返回该族记录。
         *
         *     无此族返回空记录表（不报错——族清单就在缺省形态里，客户端可先行校验）。
         */
        get: operations["engine_catalog_api_catalog_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/vehicles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Vehicle Records
         * @description 型号检索（OI-39 ②）：GCAT lv 全库规范化子串匹配，排序透明化。
         *
         *     检索词为空时返回空表（``hits=[]``，不是错误）；内置精校模板的置顶由前端完成。
         */
        get: operations["search_vehicle_records_api_catalog_vehicles_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/vehicles/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vehicle Record
         * @description 型号已知参数集（OI-39 ③）：lv + stage_links + stages + engines 逐字段带出处。
         *
         *     按名称 + 变体**精确**定位（检索候选点选后的下一跳，不做模糊）；查无此型号 →
         *     404（``CATALOG_NOT_FOUND``）。缺失显式列出、禁止编造；``reference_only`` 提示
         *     数据缺口较多、仅可作参照。
         */
        get: operations["vehicle_record_api_catalog_vehicles_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description 查询作业快照。作业不存在时返回 404。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{key}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description 返回产物文件；不在白名单或文件缺失时 404。
         */
        get: operations["get_artifact_api_artifacts__key___file__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provenance/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provenance
         * @description 返回产物清单（provenance.json 内容），供溯源与排障（§9.2 / R-14）。
         */
        get: operations["get_provenance_api_provenance__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/motor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Motor
         * @description 导入发动机/火箭模型文件，返回带单位后缀的 SI 字段与 warnings。
         *
         *     同步响应端点（规格 §10.1：非作业、无 job_id）。multipart 表单须含名为
         *     ``file`` 的文件字段；解析失败显式报错（R-21），不静默容错。
         */
        post: operations["import_motor_api_import_motor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针。
         *
         *     M0 验收项（规格 §16）：必须返回版本号，供前端与 CI 核对后端已就绪。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aero
         * @description 气动（简化，§6.1 Aero 层）。
         *
         *     ⚠ 二者均为**工程惯例值，非权威来源**（规格表已标注）；MVP 只做简化模型，
         *     **不做 CFD**（非目标 §1.3）。缺失时按默认值并附 ``warning``。
         */
        Aero: {
            /**
             * Drag Coefficient
             * @description 阻力系数 Cd（工程惯例值，非权威来源；M4 起可用基准火箭反标定）
             */
            drag_coefficient: number;
            /**
             * Reference Area M2
             * @description 参考面积（m²；省略 = 取最大截面积，由后端派生）
             */
            reference_area_m2?: number | null;
        };
        /**
         * ArcSegment
         * @description 球冠段（圆弧）：半径端半径 R 与轴向跨度 H 唯一确定球半径 ρ=(R²+H²)/2H。
         */
        ArcSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "arc";
        };
        /**
         * AvailabilityOut
         * @description 检索候选的可用性摘要：四个概览字段各自是否可得（缺列不入摘要，§7.5）。
         */
        AvailabilityOut: {
            /**
             * Glow
             * @description 起飞质量（GCAT launch_mass_kg，§6.1 GLOW 口径）是否可得
             */
            glow: boolean;
            /**
             * Length M
             * @description 全长是否可得
             */
            length_m: boolean;
            /**
             * Diameter M
             * @description 直径是否可得
             */
            diameter_m: boolean;
            /**
             * Payload Leo Kg
             * @description LEO 运力是否可得
             */
            payload_leo_kg: boolean;
        };
        /**
         * Booster
         * @description 并联助推器（§1.7.6 OI-36 / §6.1 Booster 层）。
         *
         *     侧级 :class:`Stage` **同构复用**（含其 Engine / Tank）；级号记 **0**（与 GCAT
         *     ``LV_Min/Max_Stage`` 的助推器记法对齐，§7.3）。计算上它与芯一级构成「0 级段」
         *     （§8.5 合并规则），几何上 M4 = 周向均布侧级圆柱体、M5 = 完整捆绑布局。
         */
        Booster: {
            /** @description 侧级（同构复用 Stage 全部字段及其 Engine / Tank；级号 0） */
            stage: components["schemas"]["Stage"];
            /**
             * Count
             * @description 并联数量（OI-36；1 = 单侧助推器）
             * @default 2
             */
            count: number;
            /**
             * Layout
             * @description 捆绑布局（M4 仅周向均布；M5 扩完整布局）
             * @default radial_even
             * @constant
             */
            layout: "radial_even";
            /**
             * Separation S
             * @description 分离时刻（s，相对起飞）；省略 = 芯一级关机时刻（§6.1 Booster 层）
             */
            separation_s?: number | null;
        };
        /**
         * BoosterSummary
         * @description 构建入参里的助推器摘要（M4 简化：单一构型的周向均布组）。
         *
         *     这是**几何域的入参**，不是 :class:`aeroforge.params.schema.Booster` 的搬运：
         *     从参数层助推器取 ``count`` / 侧级 ``diameter_m`` / 侧级 ``length_m`` 折算而成。
         */
        BoosterSummary: {
            /**
             * Count
             * @description 助推器数量（周向均布的枚数）
             */
            count: number;
            /**
             * Diameter M
             * @description 单枚助推器直径（m）
             */
            diameter_m: number;
            /**
             * Length M
             * @description 单枚助推器长度（m；轴向基线 = 0 起算）
             */
            length_m: number;
        };
        /**
         * BuildResponse
         * @description ``POST /api/geometry/build`` 的响应体（§9.3 缓存优先）。
         */
        BuildResponse: {
            /**
             * Cache Hit
             * @description True 表示产物已存在，metrics 直接可用，未创建作业
             */
            cache_hit: boolean;
            /**
             * Key
             * @description 内容寻址缓存键（sha256 十六进制）
             */
            key: string;
            /**
             * Job Id
             * @description 未命中时返回；用 /ws/jobs/{job_id} 订阅进度
             */
            job_id?: string | null;
            /**
             * Metrics
             * @description 命中时的产物指标
             */
            metrics?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CheckResult
         * @description 单项检查结果。
         */
        CheckResult: {
            /**
             * Check
             * @description 检查项名称
             */
            check: string;
            /**
             * Severity
             * @description 裁定：pass / warn / fail / skip
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
            /**
             * Detail
             * @description 人类可读的说明
             */
            detail: string;
            /**
             * Value
             * @description 实测值
             */
            value?: number | null;
            /**
             * Expected
             * @description 期望值
             */
            expected?: number | null;
            /**
             * Relative Error
             * @description 相对误差
             */
            relative_error?: number | null;
        };
        /**
         * ContourResponse
         * @description 母线响应体。``canonical`` 即落盘内容，往返一致的判据（规格 §16.3）。
         */
        ContourResponse: {
            /** Id */
            id: string;
            /**
             * Canonical
             * @description canonical JSON：键序固定、浮点定量、无多余空白
             */
            canonical: string;
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * ContourSaveRequest
         * @description 保存母线的请求体。
         */
        ContourSaveRequest: {
            /**
             * Id
             * @description 母线标识；省略时按 name 派生或随机生成
             */
            id?: string | null;
            /** @description 母线剖面（段链，单位米） */
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * DiagnoseResponse
         * @description ``POST /api/params/diagnose`` 的响应体。
         *
         *     ``constraints`` 只可能含**非硬**裁定：硬违反一律走 422，故前端在 200 里看到的
         *     每一条都是"警告级或更轻"，不需要再判一次"是不是该拒绝"。
         */
        DiagnoseResponse: {
            /**
             * Constraints
             * @description §6.3 的四类约束裁定（进入 200 时必为非硬）
             */
            constraints: components["schemas"]["Diagnostic"][];
            /**
             * Diagnostics
             * @description §6.5 规则集产出的诊断（六字段；impact 按 OI-11 归 M4）
             */
            diagnostics: components["schemas"]["Diagnostic"][];
            /**
             * Rules
             * @description §6.5 逐规则账目，含**未判定**的规则与其原因（不得省略）
             */
            rules: components["schemas"]["RuleOutcome"][];
        };
        /**
         * Diagnostic
         * @description 一条字段级裁定（校验错误或方案诊断）。
         */
        Diagnostic: {
            /**
             * Level
             * @description 裁定：hard = 拒绝（硬约束）；warning = 警告
             * @enum {string}
             */
            level: "hard" | "warning";
            /**
             * Code
             * @description 机器可读的判定码，如 PARAMS_FILL_OVERFILL / TWR_TOO_LOW
             */
            code: string;
            /**
             * Field Path
             * @description 字段路径（如 stages[0].engine.mixture_ratio）；整箭层判定用 vehicle 前缀
             */
            field_path: string;
            /**
             * Message
             * @description 面向用户的中文说明：实测值是多少、为什么不行
             */
            message: string;
            /**
             * Suggestion
             * @description 可操作的修复建议（§10.3 要求必填，禁止「未知错误」）
             */
            suggestion: string;
        };
        /**
         * DisplayUnitOut
         * @description 一个量的显示口径（§6.4 表逐行）。
         */
        DisplayUnitOut: {
            /**
             * Quantity
             * @description 量（规格 §6.4 表的「量」列）
             * @enum {string}
             */
            quantity: "force" | "mass" | "length" | "isp" | "velocity" | "pressure" | "temperature" | "density";
            /**
             * Label
             * @description 中文名（规格原文）
             */
            label: string;
            /**
             * Symbol
             * @description 显示单位符号（界面与导出用）
             */
            symbol: string;
            /**
             * Si Symbol
             * @description 内部 SI 符号（存储 / 计算 / 缓存键用）
             */
            si_symbol: string;
            /**
             * Factor
             * @description 换算系数，方向固定 **SI = 显示值 × factor**（方向写反是本表最易犯的错）
             */
            factor: number;
        };
        /**
         * EllipseSegment
         * @description 椭圆弧段：半轴 = (半径端半径 R, 轴向跨度 H)，椭圆心在轴线上。
         */
        EllipseSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ellipse";
        };
        /**
         * Engine
         * @description 发动机（§6.1 Engine 层）。混合比是箱体比例派生的输入（§5.9）。
         */
        Engine: {
            /**
             * Model
             * @description 型号
             */
            model: string;
            /**
             * Propellant Phase
             * @description 推进剂相态（§1.7.3 OI-30）：§6.5 起飞推重比**固体档（1.5）的唯一判据**。默认 liquid —— 实际采用的档位会印在推重比规则的账目里，故非隐式判定
             * @default liquid
             * @enum {string}
             */
            propellant_phase: "liquid" | "solid" | "hybrid";
            /**
             * Cycle
             * @description 循环方式
             * @enum {string}
             */
            cycle: "gas_generator" | "staged_combustion" | "expander" | "pressure_fed";
            /**
             * Chamber Pressure Pa
             * @description 室压
             */
            chamber_pressure_pa: number;
            /**
             * Expansion Ratio
             * @description 喷管膨胀比 ε（面积比）
             */
            expansion_ratio: number;
            /**
             * Efficiency Factor
             * @description 效率因子（c* 或 C_F 效率，1.0 = 理想）
             */
            efficiency_factor: number;
            /**
             * Thrust Sea Level N
             * @description 海平面推力（ISA 标准海平面：海拔 0 m、15 °C、101.325 kPa）
             */
            thrust_sea_level_n: number;
            /**
             * Thrust Vacuum N
             * @description 真空推力（理想真空、背压 0 的理论值）
             */
            thrust_vacuum_n: number;
            /**
             * Isp Sea Level S
             * @description 海平面比冲（ISA 标准海平面：海拔 0 m、15 °C、101.325 kPa）
             */
            isp_sea_level_s: number;
            /**
             * Isp Vacuum S
             * @description 真空比冲（理想真空、背压 0 的理论值）
             */
            isp_vacuum_s: number;
            /**
             * Mixture Ratio
             * @description 混合比 O/F（氧化剂/燃料 质量比）——§5.9 箱体比例派生的唯一输入
             */
            mixture_ratio: number;
        };
        /**
         * EngineFamilySummary
         * @description 族谱清单中的一行：族名 + 计数。
         */
        EngineFamilySummary: {
            /**
             * Family
             * @description 族名（GCAT engines 的 family 列）
             */
            family: string;
            /**
             * Count
             * @description 该族的发动机记录数
             */
            count: number;
        };
        /**
         * EngineFieldsOut
         * @description 发动机（GCAT engines 行）的逐字段投影——字段名与仓储 ``EngineRecord`` 一致。
         *
         *     ⚠ 两个口径注记（OI-35）：``isp_vacuum_s`` 为真空口径；``typical_thrust_n``
         *     环境未声明——二者只作参照展示，禁止据此派生推重比或海平面/真空换算。
         */
        EngineFieldsOut: {
            /** @description 发动机型号 */
            name: components["schemas"]["SourcedField"];
            /** @description 制造商（GCAT 机构代码原样） */
            manufacturer: components["schemas"]["SourcedField"];
            /** @description 族名 */
            family: components["schemas"]["SourcedField"];
            /** @description 氧化剂（源值原样） */
            oxidizer: components["schemas"]["SourcedField"];
            /** @description 燃料（源值原样） */
            fuel: components["schemas"]["SourcedField"];
            /** @description 满装质量（kg，官方口径：仅固体） */
            loaded_mass_kg: components["schemas"]["SourcedField"];
            /** @description 总冲（N·s，多为固体） */
            total_impulse_ns: components["schemas"]["SourcedField"];
            /** @description 典型推力（N）——⚠ source 注明「环境未声明（OI-35）」，不参与配对 */
            typical_thrust_n: components["schemas"]["SourcedField"];
            /** @description 真空比冲（s）——⚠ source 注明「真空口径（OI-35）」 */
            isp_vacuum_s: components["schemas"]["SourcedField"];
            /** @description 典型工作时间（s） */
            burn_duration_s: components["schemas"]["SourcedField"];
            /** @description 首次飞行（GCAT Date 列 TEXT 原样） */
            first_flight: components["schemas"]["SourcedField"];
            /** @description 用途/状态备注（GCAT Usage 列 TEXT 原样） */
            usage_notes: components["schemas"]["SourcedField"];
        };
        /**
         * EngineRecordOut
         * @description 族谱里的一台发动机（GCAT engines 行的读取侧投影）。
         *
         *     ⚠ 不含任何派生字段：推重比**不派生**——``typical_thrust_n`` 环境未声明
         *     （OI-35），代入任何配对计算都是编造。
         */
        EngineRecordOut: {
            /**
             * Record Id
             * @description 记录主键（溯源锚点，provenance 用）
             */
            record_id: number;
            /**
             * Name
             * @description 型号名称
             */
            name: string;
            /**
             * Manufacturer
             * @description 制造商（机构代码，经 orgs 可解析）
             */
            manufacturer: string | null;
            /**
             * Family
             * @description 族名
             */
            family: string | null;
            /**
             * Oxidizer
             * @description 氧化剂（源值原样）
             */
            oxidizer: string | null;
            /**
             * Fuel
             * @description 燃料（源值原样）
             */
            fuel: string | null;
            /**
             * Loaded Mass Kg
             * @description 满装质量（kg，官方口径：仅固体；GCAT 文档明载为 loaded）
             */
            loaded_mass_kg: number | null;
            /**
             * Total Impulse Ns
             * @description 总冲（N·s，多为固体）
             */
            total_impulse_ns: number | null;
            /**
             * Typical Thrust N
             * @description 典型推力（N）——⚠ 环境未声明，不参与配对（OI-35）；与推力/总冲禁止互称
             */
            typical_thrust_n: number | null;
            /**
             * Isp Vacuum S
             * @description 真空比冲（s，官方定义 'vacuum Isp where available'）
             */
            isp_vacuum_s: number | null;
            /**
             * Burn Duration S
             * @description 典型工作时间（s）
             */
            burn_duration_s: number | null;
            /**
             * First Flight
             * @description 首次飞行（GCAT Date 列 TEXT 原样，含 ? 尾标等可信度痕迹）
             */
            first_flight: string | null;
            /**
             * Usage Notes
             * @description 用途 / 状态备注（GCAT Usage 列 TEXT 原样）
             */
            usage_notes: string | null;
            /**
             * Quality
             * @description §7.6 质量标签（GCAT 全库为 literature）
             */
            quality: string;
        };
        /**
         * EnginesCatalogResponse
         * @description ``GET /api/catalog/engines`` 的响应体（两种形态按 ``family`` 参数分岔）。
         *
         *     - 缺省：``families`` 非空（族清单 + 计数），``engines`` 为空；
         *     - 给 ``family``：回显 ``family``，``missing_fields`` 恒在，``engines`` 为该族记录。
         */
        EnginesCatalogResponse: {
            /** @description 目录库的快照来源（§7.8 溯源锚点） */
            snapshot: components["schemas"]["SnapshotOut"];
            /**
             * Family
             * @description 查询的族名（仅在按族查询时回显；缺省查询为 null）
             */
            family?: string | null;
            /**
             * Families
             * @description 族清单 + 每族计数（缺省查询时返回；仅列确有发动机记录的族）
             * @default []
             */
            families: components["schemas"]["EngineFamilySummary"][];
            /**
             * Missing Fields
             * @description GCAT 结构性缺失、须 §7.9 手动补录的字段（按族查询时恒在；禁止编造数值）
             * @default []
             */
            missing_fields: string[];
            /**
             * Engines
             * @description 族内发动机记录（按族查询时返回；无此族为空表）
             * @default []
             */
            engines: components["schemas"]["EngineRecordOut"][];
        };
        /**
         * ErrorBody
         * @description §10.3 规定的错误响应体。
         */
        ErrorBody: {
            /**
             * Code
             * @description 机器可读的错误码，如 GEOMETRY_G1_DISCONTINUITY
             */
            code: string;
            /**
             * Stage
             * @description 发生阶段：params / meridian / solid / mesh / step / …
             */
            stage: string;
            /**
             * Message
             * @description 面向用户的中文说明
             */
            message: string;
            /**
             * Details
             * @description 结构化上下文
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Suggestion
             * @description 可操作的修复建议（规格 §10.3 要求必填）
             */
            suggestion: string;
        };
        /**
         * Geometry
         * @description 构型（§6.1 Geometry 层），**每级一个**。
         *
         *     整箭外轮廓（§5.2 的母线段列表）挂在 :attr:`Vehicle.profile`：M1 的母线描述的是
         *     **整箭纵剖面**，而共底 / 储箱排列 / 两箱本身是**逐级**属性——若把二者放进一个
         *     ``Geometry``，多级火箭就会出现"一份轮廓对应多个构型"的歧义。
         *
         *     ⚠ 装配关系（§6.1 的示例字段之一）**不在此层**：它随 M5 装配树一并建模（§16）。
         */
        Geometry: {
            /**
             * Common Bulkhead
             * @description 共底设计开关（§5.9 默认关闭）
             * @default false
             */
            common_bulkhead: boolean;
            /**
             * Common Bulkhead Type
             * @description 共底类型（共底开启时必填，由约束引擎判定）
             */
            common_bulkhead_type?: ("insulated_sandwich" | "plain") | null;
            /**
             * Tank Arrangement
             * @description 储箱排列（§5.9 非铁律，用户可配置）
             * @default oxidizer_upper
             * @enum {string}
             */
            tank_arrangement: "oxidizer_upper" | "fuel_upper";
            /**
             * Fins Enabled
             * @description 尾翼 / 稳定面是否启用
             * @default false
             */
            fins_enabled: boolean;
            /** @description 氧化剂箱 */
            oxidizer_tank: components["schemas"]["Tank"];
            /** @description 燃料箱 */
            fuel_tank: components["schemas"]["Tank"];
        };
        /**
         * GeometryBuildRequest
         * @description ``POST /api/geometry/build`` 的**捆绑构型**请求体（OI-36，M4 简化摘要）。
         *
         *     与裸剖面请求体并存：省略 ``boosters`` 即等价于旧的裸剖面请求——
         *     既有客户端的构建路径与缓存键逐字节不变（§9.2）。
         */
        GeometryBuildRequest: {
            /** @description 母线剖面（段链，单位米） */
            profile: components["schemas"]["MeridianProfile"];
            /** @description M4 简化捆绑摘要（OI-36：count / 直径 / 长度，周向均布）；省略 = 无助推器，GLB 场景图只含 seg-<i> 节点 */
            boosters?: components["schemas"]["BoosterSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/health`` 的响应体。
         *
         *     作为 OpenAPI schema 的来源，前端 TS 类型由此生成（规格 §18.2：禁止手写重复类型）。
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * JobRecord
         * @description 作业状态快照（跨线程传递的**纯数据**，不含任何几何对象）。
         */
        JobRecord: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** @default queued */
            stage: components["schemas"]["JobStage"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Result Key */
            result_key?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
        };
        /**
         * JobStage
         * @description §9.3 的进度阶段（M1 子集：几何链 ``meridian → solid → mesh → step → done``）。
         * @enum {string}
         */
        JobStage: "queued" | "meridian" | "solid" | "mesh" | "step" | "done";
        /**
         * JobStatus
         * @description §9.3 的作业生命周期状态。
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JointCheck
         * @description 段间接头（G0 由结构保证，此处校 G1）。
         */
        JointCheck: {
            /**
             * Index
             * @description 接头序号：段 index 与 index+1 之间
             */
            index: number;
            /** Z */
            z: number;
            /** Radius */
            radius: number;
            /**
             * Angle Deg
             * @description 两侧切向夹角（度）
             */
            angle_deg: number;
            /**
             * Kind
             * @description g1 = 常规切向；pinch = 轴处反向尖点
             * @enum {string}
             */
            kind: "g1" | "pinch";
            /**
             * Severity
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
        };
        /**
         * LaunchSite
         * @description 发射场（§6.1 LaunchSite 层）。
         *
         *     纬度是**自转加成与转向损失的唯一输入**（§8.6）：计算中不得另设常量，
         *     否则"改纬度运力不变"这类缺陷会在任何一处悄悄复现。
         */
        LaunchSite: {
            /**
             * Name
             * @description 发射场名称
             */
            name: string;
            /**
             * Latitude Deg
             * @description 纬度（°，北正南负）
             */
            latitude_deg: number;
            /**
             * Altitude M
             * @description 海拔（m，可为负）
             */
            altitude_m: number;
            /**
             * Azimuth Deg
             * @description 发射方位角（°，自正北顺时针；默认值，可被 Mission 覆盖）
             */
            azimuth_deg: number;
        };
        /**
         * LineSegment
         * @description 直线段：柱段（end_radius == 起点半径）或锥段/锥台。
         */
        LineSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "line";
        };
        /**
         * LossFactors
         * @description ΔV 损失项系数（§8.6 的损失构成）。
         *
         *     M2 只做**存储与透传**；损失模型 L1 的实算属 M4（§16）。刻意**不设默认值猜测**：
         *     缺省即 0 并在结果中标注为"未计入"，而不是填一个看着合理的经验数（§1.4-4）。
         */
        LossFactors: {
            /**
             * Gravity
             * @description 重力损失（Δv 份额）
             * @default 0
             */
            gravity: number;
            /**
             * Drag
             * @description 气动阻力损失（Δv 份额）
             * @default 0
             */
            drag: number;
            /**
             * Steering
             * @description 转向损失（Δv 份额）
             * @default 0
             */
            steering: number;
            /**
             * Back Pressure
             * @description 背压损失（与「压力/控制余量」同义，§8.8）
             * @default 0
             */
            back_pressure: number;
        };
        /**
         * MaterialOut
         * @description 一条材料记录（§7.4 材料库表 + 派生比强度 / 比刚度计算值）。
         */
        MaterialOut: {
            /**
             * Id
             * @description 材料 id（Schema material 字段的引用值）
             */
            id: string;
            /**
             * Name
             * @description 牌号名（含热处理态）
             */
            name: string;
            /**
             * Category
             * @description 类别：铝合金 / 不锈钢 / 钛合金 / 复材 / 高温合金
             * @enum {string}
             */
            category: "铝合金" | "不锈钢" | "钛合金" | "复材" | "高温合金";
            /**
             * Density Kg M3
             * @description 密度（kg/m³）
             */
            density_kg_m3: number;
            /**
             * Elastic Modulus Pa
             * @description 弹性模量（Pa，室温）
             */
            elastic_modulus_pa: number;
            /**
             * Yield Strength Pa
             * @description 屈服强度（Pa，室温典型值；复材为许用典型）
             */
            yield_strength_pa: number;
            /**
             * Service Temp Min C
             * @description 工作温度下限（°C，量级表述）
             */
            service_temp_min_c: number;
            /**
             * Service Temp Max C
             * @description 工作温度上限（°C，量级表述）
             */
            service_temp_max_c: number;
            /**
             * Typical Min Wall Thickness M
             * @description 典型工艺壁厚下限（m，工程惯例典型值；壁厚判据未显式配置时的回落档）
             */
            typical_min_wall_thickness_m: number;
            /**
             * Heat Treatment
             * @description 热处理 / 试验条件（同一合金不同状态性能差数倍）
             */
            heat_treatment: string;
            /**
             * Source
             * @description 出处文字（公开手册 / 标准 / 厂商 datasheet）；typical 条目可为 null
             */
            source: string | null;
            /**
             * Quality
             * @description 质量标签：literature = 实测手册值；typical = 工程典型值（不得用于结论性导出）
             * @enum {string}
             */
            quality: "literature" | "typical";
            /**
             * Specific Strength M2 S2
             * @description 比强度 σ_y/ρ（m²/s²，即 N·m/kg）——派生计算值，不随库存储（P1）
             */
            specific_strength_m2_s2: number;
            /**
             * Specific Stiffness M2 S2
             * @description 比刚度 E/ρ（m²/s²，即 N·m/kg）——派生计算值，不随库存储（P1）
             */
            specific_stiffness_m2_s2: number;
        };
        /**
         * MaterialsResponse
         * @description ``GET /api/catalog/materials`` 的响应体。
         */
        MaterialsResponse: {
            /**
             * Materials
             * @description 材料库全量（§7.4 自建库）
             */
            materials: components["schemas"]["MaterialOut"][];
        };
        /**
         * MeridianProfile
         * @description 母线剖面：底部半径 + 自下而上的段链（规格 §5.2）。
         *
         *     剖面在 (r, z) 平面内描述，回转轴为 Z 轴，单位米。
         *     实体 = 区域 ``{(r, z)}`` 绕 Z 轴回转 360°，其中区域由
         *     ``(0,0) → (base_radius,0) → [段链] → (r_end,z_end) → (0,z_end) → (0,0)`` 围成。
         */
        MeridianProfile: {
            /**
             * Name
             * @description 剖面名称（仅用于展示，不参与几何）
             * @default
             */
            name: string;
            /**
             * Base Radius
             * @description z=0 处的半径（m）
             */
            base_radius: number;
            /**
             * Segments
             * @description 自下而上的段链
             */
            segments: (components["schemas"]["LineSegment"] | components["schemas"]["ArcSegment"] | components["schemas"]["EllipseSegment"])[];
        };
        /**
         * Mission
         * @description 任务与轨道要素（§6.1 Mission 层；轨道要素由 OI-21 补入）。
         */
        Mission: {
            /**
             * Orbit Type
             * @description 目标轨道类型
             * @enum {string}
             */
            orbit_type: "LEO" | "SSO" | "GTO" | "GEO" | "TLI" | "TMI" | "escape" | "custom";
            /**
             * Altitude M
             * @description 圆轨道高度（LEO / SSO / GEO 用）
             */
            altitude_m?: number | null;
            /**
             * Inclination Deg
             * @description 轨道倾角（°）
             */
            inclination_deg?: number | null;
            /**
             * Eccentricity
             * @description 偏心率
             */
            eccentricity?: number | null;
            /**
             * Perigee Altitude M
             * @description 近地点高度（GTO / TLI / TMI 用）
             */
            perigee_altitude_m?: number | null;
            /**
             * Apogee Altitude M
             * @description 远地点高度（GTO / TLI / TMI 用）
             */
            apogee_altitude_m?: number | null;
            /** @description 内联发射场（与 id 二选一） */
            launch_site?: components["schemas"]["LaunchSite"] | null;
            /**
             * Launch Site Id
             * @description 发射场引用（与内联二选一）
             */
            launch_site_id?: string | null;
            /** @description ΔV 损失项系数（§8.6） */
            loss_factors?: components["schemas"]["LossFactors"] | null;
            /**
             * Wind Profile Ref
             * @description 风廓线引用（M6，可空）
             */
            wind_profile_ref?: string | null;
        };
        /**
         * MotorParseResult
         * @description 发动机解析结果（``.eng`` / ``.rse`` 同构）。字段名带 SI 单位后缀。
         */
        MotorParseResult: {
            /**
             * Format
             * @enum {string}
             */
            format: "eng" | "rse";
            /**
             * Name
             * @description 发动机型号（.eng 表头首列 / .rse 的 code 属性）
             */
            name: string;
            /**
             * Manufacturer
             * @description 制造商（仅 .rse 提供）
             */
            manufacturer?: string | null;
            /**
             * Motor Type
             * @description 发动机类型（仅 .rse 的 type 属性）
             */
            motor_type?: string | null;
            /**
             * Delays
             * @description 可用延时（数字或 P=堵死）
             */
            delays?: string[];
            /**
             * Total Impulse Ns
             * @description 总冲（N·s，曲线梯形积分）
             */
            total_impulse_ns: number;
            /**
             * Burn Time S
             * @description 燃烧时间（s，曲线末点时间）
             */
            burn_time_s: number;
            /**
             * Avg Thrust N
             * @description 平均推力（N，总冲 ÷ 燃烧时间）
             */
            avg_thrust_n: number;
            /**
             * Peak Thrust N
             * @description 峰值推力（N）
             */
            peak_thrust_n: number;
            /**
             * Propellant Mass Kg
             * @description 推进剂质量（kg，有则给出）
             */
            propellant_mass_kg?: number | null;
            /**
             * Total Mass Kg
             * @description 总质量（kg，有则给出）
             */
            total_mass_kg?: number | null;
            /**
             * Thrust Curve
             * @description 推力曲线（已统一为 SI）
             */
            thrust_curve: components["schemas"]["ThrustPoint"][];
            /**
             * Warnings
             * @description 可疑内容清单（R-21：不静默）
             */
            warnings?: string[];
            /**
             * Unit Conversions
             * @description 逐条单位换算声明（§7.5：显式声明源单位）
             */
            unit_conversions?: string[];
            /**
             * Derived
             * @description 是否为推导值（.eng/.rse 为 False）
             * @default false
             */
            derived: boolean;
        };
        /**
         * Recovery
         * @description 回收与复用（§6.1 Recovery 层）。
         */
        Recovery: {
            /**
             * Enabled
             * @description 是否回收
             * @default false
             */
            enabled: boolean;
            /**
             * Stage Indices
             * @description 回收的级号
             * @default []
             */
            stage_indices: number[];
            /**
             * Method
             * @description 回收方式
             */
            method?: ("parachute" | "propulsive") | null;
            /**
             * Landing Propellant Margin Fraction
             * @description 着陆推进剂余量（占该级满装量）
             */
            landing_propellant_margin_fraction?: number | null;
            /**
             * System Mass Kg
             * @description 回收系统质量代价
             */
            system_mass_kg?: number | null;
        };
        /**
         * RocketParseResult
         * @description ``.ork`` 火箭解析结果。**一切字段均为 derived**（规格 §7.5）。
         */
        RocketParseResult: {
            /**
             * Format
             * @constant
             */
            format: "ork";
            /** Name */
            name: string;
            /**
             * Derived
             * @description 恒为 True：.ork 结果不保证全字段保真
             * @default true
             */
            derived: boolean;
            /** Stage Count */
            stage_count: number;
            /** Stages */
            stages: components["schemas"]["RocketStage"][];
            /**
             * Warnings
             * @description 未识别元素等报告（R-21）
             */
            warnings?: string[];
        };
        /**
         * RocketStage
         * @description ``.ork`` 中的一级（字段仅在该级可用时给出，§7.5：不保证全字段保真）。
         */
        RocketStage: {
            /** Name */
            name: string;
            /** Length M */
            length_m?: number | null;
            /** Diameter M */
            diameter_m?: number | null;
            /** Mass Kg */
            mass_kg?: number | null;
            /**
             * Engines
             * @description 该级发动机型号列表
             */
            engines?: string[];
        };
        /**
         * RuleOutcome
         * @description 一条 §6.5 规则的执行账目——**含未判定的部分**。
         */
        RuleOutcome: {
            /**
             * Code
             * @description 规则判定码
             */
            code: string;
            /**
             * Title
             * @description 规则名（§6.5 表「规则」列）
             */
            title: string;
            /**
             * Level
             * @description 该规则违反时的级别（§6.5 表「级别」列）
             * @enum {string}
             */
            level: "hard" | "warning";
            /**
             * Threshold
             * @description 本次实际生效的阈值（含来源标注）
             */
            threshold: string;
            /**
             * Source
             * @description 阈值来源标注（§6.5 强制携带）
             */
            source: string;
            /**
             * Diagnostics
             * @description 本规则产出的裁定；空 = 该规则通过
             * @default []
             */
            diagnostics: components["schemas"]["Diagnostic"][];
            /**
             * Deferred Reason
             * @description **整条规则**未判定的原因（缺输入 / 属后续里程碑）
             */
            deferred_reason?: string | null;
            /**
             * Uncovered
             * @description 规则已判、但**判据分支**未启用的说明（空 = 全覆盖）
             * @default []
             */
            uncovered: string[];
        };
        /**
         * Sequence
         * @description 任务时序（§6.1 Sequence 层）。
         */
        Sequence: {
            /**
             * Events
             * @description 事件列表（按发生顺序）
             */
            events: components["schemas"]["SequenceEvent"][];
        };
        /**
         * SequenceEvent
         * @description 一个任务时序事件（§6.1 Sequence 层）。
         */
        SequenceEvent: {
            /**
             * Event
             * @description 事件类型
             * @enum {string}
             */
            event: "ignition" | "stage_separation" | "fairing_jettison" | "orbit_insertion" | "landing";
            /**
             * Time S
             * @description 相对时刻（s）
             */
            time_s?: number | null;
            /**
             * Trigger
             * @description 触发条件（自由文本，如「燃尽压降 5%」）
             */
            trigger?: string | null;
            /**
             * Stage Index
             * @description 关联级号（可空）
             */
            stage_index?: number | null;
        };
        /**
         * SnapshotOut
         * @description 本目录库的快照来源（§7.8：数值随 provenance 下发的锚点）。
         */
        SnapshotOut: {
            /**
             * Id
             * @description 快照 id（如 gcat-2026Q3）
             */
            id: string;
            /**
             * Release
             * @description GCAT release 号
             */
            release: string;
            /**
             * Total Records
             * @description 快照登记的总记录数（六表合计）
             */
            total_records: number;
        };
        /**
         * SourcedField
         * @description 单个已知参数字段：值 + 出处锚点 + 单位存疑标记（§7.8 溯源红线）。
         *
         *     ``value`` 为 ``null`` 表示 GCAT 源缺失——**缺失是状态不是 0**（§7.5 规则 2），
         *     一律入响应顶层的 ``missing`` 清单，禁止编造替代值。
         */
        SourcedField: {
            /**
             * Value
             * @description 字段值（ETL 已换算 SI；GCAT 缺失为 null，禁止编造）
             */
            value: number | string | null;
            /**
             * Source
             * @description 出处锚点，如 "GCAT gcat-2026Q3 lv#175"（表前缀 lv/st/en + 源行号）
             */
            source: string;
            /**
             * Unit Uncertain
             * @description 该字段是否被 ETL 标记单位/量值存疑（解析失败或出合理区间，值仍保留原样）
             */
            unit_uncertain: boolean;
        };
        /**
         * Stage
         * @description 单级（§6.1 Stage 层）。自下而上编号，``index`` 1 = 第一级。
         */
        Stage: {
            /**
             * Index
             * @description 级序号：1 = 第一级（自下而上）
             */
            index: number;
            /**
             * Propellant
             * @description 该级推进剂组合
             * @enum {string}
             */
            propellant: "LOX/RP-1" | "LOX/LH2" | "LOX/CH4" | "N2O4/UDMH" | "N2O4/MMH";
            /**
             * Diameter M
             * @description 级直径
             */
            diameter_m: number;
            /**
             * Length M
             * @description 级高度（含级间段）
             */
            length_m: number;
            /**
             * Flatness Ratio
             * @description 扁度系数（OI-37）：贮箱封头椭球的短长轴比；省略 = 按 0.5（2:1 椭圆封头）处理。只影响封头矢高与共底缩减量，不与「高度」重复定长（几何生效于 M5）
             */
            flatness_ratio?: number | null;
            /**
             * Wall Thickness M
             * @description 级壁厚
             */
            wall_thickness_m: number;
            /**
             * Material
             * @description 材料库引用（/api/catalog/materials；值须为库内材料 id）
             */
            material: string;
            /**
             * Structure Coefficient
             * @description 结构系数 σ = m_dry/(m_dry+m_prop)（**存储权威**，§6.1）
             */
            structure_coefficient: number;
            /**
             * Fill Fraction
             * @description 加注比例（上限 1.0，OI-03）
             */
            fill_fraction: number;
            /**
             * Max Fill Mass Kg
             * @description 最大允许加注量（仅超装场景显式启用）
             */
            max_fill_mass_kg?: number | null;
            /**
             * Engine Count
             * @description 发动机台数
             */
            engine_count: number;
            /** @description 该级发动机定义 */
            engine: components["schemas"]["Engine"];
            /**
             * Engine Height M
             * @description 发动机高度（安装基准面 → 喷管出口端面，含喷管）
             */
            engine_height_m: number;
            /**
             * Engine Height Nozzle Excluded M
             * @description 发动机高度（不含喷管）
             */
            engine_height_nozzle_excluded_m?: number | null;
            /**
             * Burn Time S
             * @description 工作时间（s）；省略时由后端按 m_prop/ṁ 派生
             */
            burn_time_s?: number | null;
            /**
             * Interstage Type
             * @description 级间段类型（该级与其**上级之间**的分离段；不是级间舱，§5.9 共性 2）
             * @enum {string}
             */
            interstage_type: "cold_staging" | "hot_staging" | "none";
            /**
             * Isp Vacuum S
             * @description 该级真空比冲（仅 isp_source=custom 时填写；省略 = 取发动机标称值）
             */
            isp_vacuum_s?: number | null;
            /**
             * Isp Sea Level S
             * @description 该级海平面比冲（仅 isp_source=custom 时填写；省略 = 取发动机标称值）
             */
            isp_sea_level_s?: number | null;
            /**
             * Isp Source
             * @description 比冲来源：default = 取自 engine 定义（省略 isp_* 字段）；custom = 用户覆写（必填）
             * @enum {string}
             */
            isp_source: "default" | "custom";
            /**
             * Recoverable
             * @description 可回收性（回收方案见 Recovery 层）
             * @default false
             */
            recoverable: boolean;
            /** @description 该级构型（共底 / 储箱排列 / 两箱） */
            geometry: components["schemas"]["Geometry"];
        };
        /**
         * StageAssemblyOut
         * @description 一条装配行：stage_links 关系 + 该级的逐字段投影（缺失引用时 ``record`` 为 null）。
         */
        StageAssemblyOut: {
            /**
             * Stage No
             * @description 级号（stage_links 的 Stage_No 原样，含空格）
             */
            stage_no: string | null;
            /**
             * Qualifier
             * @description 限定符（stage_links 原样）
             */
            qualifier: string | null;
            /** @description 级记录投影；null = 缺失引用（stage_links 指向的级不在 stages 表，不编造） */
            record: components["schemas"]["StageFieldsOut"] | null;
            /**
             * Missing Reference
             * @description 是否缺失引用（与 record 为 null 同步）
             */
            missing_reference: boolean;
        };
        /**
         * StageFieldsOut
         * @description 级（GCAT stages 行）的逐字段投影——字段名与仓储 ``StageRecord`` 一致。
         *
         *     推力真空/海平面分列（§7.5 规则 3 / OI-35）；比冲 GCAT 不提供（结构性缺失）。
         */
        StageFieldsOut: {
            /** @description 级名称 */
            name: components["schemas"]["SourcedField"];
            /** @description 级族 */
            family: components["schemas"]["SourcedField"];
            /** @description 制造商（GCAT 机构代码原样） */
            manufacturer: components["schemas"]["SourcedField"];
            /** @description 级长（m） */
            length_m: components["schemas"]["SourcedField"];
            /** @description 级直径（m） */
            diameter_m: components["schemas"]["SourcedField"];
            /** @description 级满装质量（kg） */
            full_mass_kg: components["schemas"]["SourcedField"];
            /** @description 级干重（kg） */
            dry_mass_kg: components["schemas"]["SourcedField"];
            /** @description 级真空推力（N，§7.5 规则 3） */
            thrust_vacuum_n: components["schemas"]["SourcedField"];
            /** @description 级海平面推力（N，§7.5 规则 3） */
            thrust_sea_level_n: components["schemas"]["SourcedField"];
            /** @description 工作时间（s） */
            burn_duration_s: components["schemas"]["SourcedField"];
            /** @description 级引用的发动机名（GCAT 原样） */
            engine_name: components["schemas"]["SourcedField"];
            /** @description 发动机台数 */
            engine_count: components["schemas"]["SourcedField"];
        };
        /**
         * Tank
         * @description 贮箱（§6.1 Tank 层）。
         *
         *     ``volume_m3`` / ``nominal_full_mass_kg`` / ``liquid_level_m`` 是**派生量**，
         *     不在此层存储（唯一权威原则）——它们由后端算出并随结果下发。
         */
        Tank: {
            /**
             * Tank Type
             * @description 贮箱类型：非共底 / 共底
             * @enum {string}
             */
            tank_type: "separate" | "common_bulkhead";
            /**
             * Diameter M
             * @description 贮箱直径（省略 = 继承该级直径）
             */
            diameter_m?: number | null;
            /**
             * Length M
             * @description 用户显式给定的箱长（省略 = 由后端按 §5.9 派生）
             */
            length_m?: number | null;
            /**
             * Wall Thickness M
             * @description 壁厚
             */
            wall_thickness_m: number;
            /**
             * Material
             * @description 材料库引用（/api/catalog/materials；值须为库内材料 id）
             */
            material: string;
            /**
             * Fill Fraction
             * @description 加注比例 = 实际加注量 / 满装量；上限 1.0（OI-03，由约束引擎判定）
             */
            fill_fraction: number;
            /**
             * Max Fill Mass Kg
             * @description 最大允许加注量（仅在超装场景显式启用，§6.1 / OI-03）
             */
            max_fill_mass_kg?: number | null;
            /**
             * Feed System
             * @description 输送方式：泵压式 / 挤压式
             * @enum {string}
             */
            feed_system: "pump_fed" | "pressure_fed";
            /**
             * Delivery Pipe Routing
             * @description 输送管走法（§5.9 默认外置沿箭体）
             * @default external
             * @enum {string}
             */
            delivery_pipe_routing: "external" | "internal";
            /**
             * Common Bulkhead Insulation M
             * @description 共底隔热层厚度（共底且 LH₂ 侧必填，§5.9 口径 2）
             */
            common_bulkhead_insulation_m?: number | null;
        };
        /**
         * TemplateDetailResponse
         * @description ``GET /api/templates/{template_id}`` 的响应体（§11.5 ⑤ 规则 2/5）。
         */
        TemplateDetailResponse: {
            /**
             * Id
             * @description 模板标识
             */
            id: string;
            /**
             * Name
             * @description 公开型号名
             */
            name: string;
            /**
             * Note
             * @description 必须原样呈现的说明（含来源声明与 §13.2 同源声明）
             */
            note: string;
            /**
             * Aliases
             * @description 别名表
             */
            aliases: string[];
            /**
             * Reference Payload Leo Kg
             * @description 公开 LEO 运力对照值（§13.2 基准表同源）
             */
            reference_payload_leo_kg: number;
            /**
             * Sourced Fields
             * @description 字段路径 → 出处（覆盖该 Vehicle 的全部数值字段）；载入后逐控件标注，用户改动任何值后该字段出处转为「用户修改」（§11.5 ⑤ 规则 5）
             */
            sourced_fields: {
                [key: string]: string;
            };
            /** @description 模板本体（已过产品校验器、无硬违反，可直接提交诊断） */
            vehicle: components["schemas"]["Vehicle"];
        };
        /**
         * TemplateListResponse
         * @description ``GET /api/templates`` 的响应体（§11.5 ⑤ OI-29）。
         */
        TemplateListResponse: {
            /**
             * Templates
             * @description 内置模板清单（当前覆盖范围与缘由见各模板 note）
             */
            templates: components["schemas"]["TemplateSummaryOut"][];
        };
        /**
         * TemplateMatchResponse
         * @description ``GET /api/templates/match`` 的响应体（§11.5 ⑤ OI-34）。
         *
         *     未命中时 ``matched=false``、其余字段为 ``null``——**不报错**：名称栏防抖会在
         *     用户输入过程中频繁发出查询，「还没打完」不是错误。
         */
        TemplateMatchResponse: {
            /**
             * Matched
             * @description 是否命中内置模板（规范化后精确等值，宁漏勿错）
             */
            matched: boolean;
            /**
             * Template Id
             * @description 命中的模板 id（未命中为 null）
             */
            template_id?: string | null;
            /**
             * Name
             * @description 命中的模板名（未命中为 null）
             */
            name?: string | null;
            /**
             * Note
             * @description 命中模板的说明（未命中为 null）
             */
            note?: string | null;
        };
        /**
         * TemplateResponse
         * @description ``GET /api/params/template`` 的响应体（界面可编辑的起始箭）。
         */
        TemplateResponse: {
            /**
             * Template Id
             * @description 骨架标识
             */
            template_id: string;
            /**
             * Label
             * @description 界面显示名（含「未经来源核对」字样）
             */
            label: string;
            /**
             * Note
             * @description 必须原样呈现的说明；不得改写为更肯定的措辞
             */
            note: string;
            /**
             * Sourced Fields
             * @description 有出处的字段路径 → 出处。**不在本表里的数值一律是占位值**（§1.4-4）；路径口径与 §6.3 / §6.5 的 field_path 逐字一致
             */
            sourced_fields: {
                [key: string]: string;
            };
            /** @description 起始箭本体（结构合法，可直接提交诊断） */
            vehicle: components["schemas"]["Vehicle"];
        };
        /**
         * TemplateSummaryOut
         * @description 清单中单个模板的元数据（不含完整参数——载入走详情端点）。
         */
        TemplateSummaryOut: {
            /**
             * Id
             * @description 模板标识（详情端点的路径参数）
             */
            id: string;
            /**
             * Name
             * @description 公开型号名
             */
            name: string;
            /**
             * Aliases
             * @description 别名表（OI-34 匹配宇宙的一部分）
             */
            aliases: string[];
            /**
             * Stage Count
             * @description 级数
             */
            stage_count: number;
            /**
             * Note
             * @description 随模板下发的说明（界面须原样呈现）
             */
            note: string;
            /**
             * Reference Payload Leo Kg
             * @description 公开 LEO 运力对照值（§13.2 基准表同源）
             */
            reference_payload_leo_kg: number;
        };
        /**
         * ThresholdEntry
         * @description 一个阈值的**生效**状态（界面设置项直接消费）。
         */
        ThresholdEntry: {
            /**
             * Key
             * @description 配置键（config.toml 的顶层键名）
             */
            key: string;
            /**
             * Label
             * @description 中文名
             */
            label: string;
            /**
             * Value
             * @description **生效值**；null = 未配置（该判据不判定）
             */
            value: number | null;
            /**
             * Source
             * @description §6.5 强制的来源标注（界面不得自拟措辞）
             */
            source: string;
            /**
             * Origin
             * @description 生效值的来源：环境变量/config.toml/默认值/未配置
             */
            origin: string;
            /**
             * Note
             * @description 生效边界说明
             */
            note: string;
        };
        /**
         * ThresholdsResponse
         * @description ``GET`` / ``PUT /api/params/thresholds`` 的响应体（§1.7.3 OI-31）。
         */
        ThresholdsResponse: {
            /**
             * Config File
             * @description 写入目标：config.toml 的完整路径（§18.4）
             */
            config_file: string;
            /**
             * Thresholds
             * @description 各项的**生效值**与来源；value 为 null 表示「未配置」（该判据不判定）
             */
            thresholds: components["schemas"]["ThresholdEntry"][];
        };
        /**
         * ThrustPoint
         * @description 推力曲线上的一个点（已统一为 SI 单位）。
         */
        ThrustPoint: {
            /**
             * Time S
             * @description 时间（s）
             */
            time_s: number;
            /**
             * Thrust N
             * @description 推力（N）
             */
            thrust_n: number;
        };
        /**
         * UnitsResponse
         * @description ``GET /api/params/units`` 的响应体（§1.7.3 OI-32）。
         */
        UnitsResponse: {
            /**
             * Units
             * @description §6.4 全表；界面**只按此格式化**，不得在前端再抄一份表或反推系数
             */
            units: components["schemas"]["DisplayUnitOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationReport
         * @description 母线层校验报告（同步接口返回体）。
         */
        ValidationReport: {
            /** Ok */
            ok: boolean;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Joints */
            joints: components["schemas"]["JointCheck"][];
            /**
             * Sample
             * @description 剖面采样点 (r, z)，米
             */
            sample: [
                number,
                number
            ][];
            /**
             * Outline
             * @description 闭合轮廓 (r, z)，米
             */
            outline: [
                number,
                number
            ][];
            /**
             * Segment Outline
             * @description **逐段**闭合轮廓 (r, z)，米——下标与 `profile.segments` 一一对应，退化段为空列表。供示意通道**逐段**建网格，与权威通道的 GLB 具名节点（`seg-<i>`）同粒度，二者才能各自隐藏同一段（OI-33 ③）
             */
            segment_outline: [
                number,
                number
            ][][];
            /**
             * Envelope
             * @description 解析包络 (2R, 2R, L)，米
             */
            envelope: [
                number,
                number,
                number
            ];
            /**
             * Volume
             * @description 解析体积（m³）
             */
            volume: number;
            /** Surface Area */
            surface_area: number;
            /** Centroid Z */
            centroid_z: number;
            /** Max Radius */
            max_radius: number;
            /** Total Length */
            total_length: number;
        };
        /**
         * Vehicle
         * @description 飞行器总纲（§6.1 Vehicle 层）——前端与后端之间传递的唯一顶层参数对象。
         *
         *     ``total_length_m`` / ``max_diameter_m`` 等**派生量不在此层**：它们由
         *     :mod:`aeroforge.params.dag` 算出并随结果下发（前端零几何计算，ADR-011）。
         */
        Vehicle: {
            /**
             * Schema Version
             * @description 参数 Schema 版本号
             * @default 1
             */
            schema_version: string;
            /**
             * Name
             * @description 火箭名称
             */
            name: string;
            /**
             * Stages
             * @description 自下而上（index 1 = 第一级）
             */
            stages: components["schemas"]["Stage"][];
            /**
             * Boosters
             * @description 并联助推器组（§1.7.6 OI-36：每项 = 侧级 Stage + 数量 + 捆绑布局；级号 0，与芯一级构成 0 级段，合并规则见 §8.5）
             */
            boosters?: components["schemas"]["Booster"][];
            /**
             * Payload Mass Kg
             * @description 有效载荷质量
             */
            payload_mass_kg: number;
            /**
             * Fairing Diameter M
             * @description 整流罩直径
             */
            fairing_diameter_m?: number | null;
            /**
             * Material
             * @description 箭体材料（全局默认，可被 Stage 覆盖）；材料库引用（/api/catalog/materials）
             */
            material: string;
            /**
             * Propellant
             * @description 推进剂组合（全局默认，可被 Stage 覆盖）
             * @enum {string}
             */
            propellant: "LOX/RP-1" | "LOX/LH2" | "LOX/CH4" | "N2O4/UDMH" | "N2O4/MMH";
            /** @description 气动（缺失时按默认值并附 warning） */
            aero?: components["schemas"]["Aero"] | null;
            /** @description 整箭母线剖面（§5.2 的 2D→3D 入口；M1 已落地） */
            profile?: components["schemas"]["MeridianProfile"] | null;
            /** @description 任务与轨道 */
            mission: components["schemas"]["Mission"];
            /** @description 任务时序 */
            sequence?: components["schemas"]["Sequence"] | null;
            /** @description 回收与复用 */
            recovery?: components["schemas"]["Recovery"] | null;
        };
        /**
         * VehicleFieldsOut
         * @description 完整火箭（GCAT lv 行）的逐字段投影——字段名与仓储 ``VehicleRecord`` 一致。
         */
        VehicleFieldsOut: {
            /** @description 型号名称 */
            name: components["schemas"]["SourcedField"];
            /** @description 型号族 */
            family: components["schemas"]["SourcedField"];
            /** @description 变体 */
            variant: components["schemas"]["SourcedField"];
            /** @description 制造商（GCAT 机构代码原样） */
            manufacturer: components["schemas"]["SourcedField"];
            /** @description 级号范围下界（助推器记 0/−1，§7.3） */
            min_stage_no: components["schemas"]["SourcedField"];
            /** @description 级号范围上界（核心级数 ≈ 此值，§7.3） */
            max_stage_no: components["schemas"]["SourcedField"];
            /** @description 全长（m） */
            length_m: components["schemas"]["SourcedField"];
            /** @description 最大直径（m） */
            diameter_m: components["schemas"]["SourcedField"];
            /** @description 起飞质量（kg，§6.1 GLOW 口径） */
            launch_mass_kg: components["schemas"]["SourcedField"];
            /** @description LEO 运力（kg） */
            payload_leo_kg: components["schemas"]["SourcedField"];
            /** @description GTO 运力（kg） */
            payload_gto_kg: components["schemas"]["SourcedField"];
            /** @description 起飞推力（N） */
            liftoff_thrust_n: components["schemas"]["SourcedField"];
            /** @description GCAT 类别码（O/B/S/R 原样） */
            vehicle_class: components["schemas"]["SourcedField"];
        };
        /**
         * VehicleRecordResponse
         * @description ``GET /api/catalog/vehicles/record`` 的响应体：型号已知参数集（OI-39 ③）。
         *
         *     - ``missing``：显式缺失清单——每个值为 null 的字段一条（路径与控件 ``field_path``
         *       同口径）+ 缺失引用条目；GCAT 没有的一律 null + missing，**禁止编造**；
         *     - ``warnings``：装配过程的非致命问题（缺失引用、同名发动机多行取首见），原样透传；
         *     - ``reference_only``：可用字段不足一半（GCAT 以 0 填未知，0 值按 §7.5「缺失是
         *       状态不是 0」计为不可用）→ true，前端应提示「仅可作参照」。
         */
        VehicleRecordResponse: {
            /**
             * Name
             * @description 型号名称（回显）
             */
            name: string;
            /**
             * Variant
             * @description 变体（回显；无变体为 null）
             */
            variant: string | null;
            /**
             * Record Id
             * @description lv 记录主键（溯源锚点）
             */
            record_id: number;
            /**
             * Quality
             * @description §7.6 质量标签（GCAT 全库为 literature）
             */
            quality: string;
            /** @description 目录库的快照来源（§7.8 溯源锚点） */
            snapshot: components["schemas"]["SnapshotOut"];
            /** @description lv 行逐字段投影（出处逐字段携带） */
            vehicle: components["schemas"]["VehicleFieldsOut"];
            /**
             * Stages
             * @description 装配行（按 Stage_No 数值序；含缺失引用的 null 槽位）
             */
            stages: components["schemas"]["StageAssemblyOut"][];
            /**
             * Engines
             * @description 本型号各级引用的发动机（按装配序去重；口径注记见字段说明）
             */
            engines: components["schemas"]["EngineFieldsOut"][];
            /**
             * Missing
             * @description 显式缺失清单（null 字段路径 + 缺失引用说明；禁止编造的缺口都在这里）
             */
            missing: string[];
            /**
             * Warnings
             * @description 装配过程的非致命问题（原样透传，不吞不掉）
             */
            warnings: string[];
            /**
             * Reference Only
             * @description 可用字段不足一半时为 true——数据缺口较多，仅可作参照，建模需手动补参
             */
            reference_only: boolean;
        };
        /**
         * VehicleSearchHitOut
         * @description 一条检索候选（GCAT lv 记录的检索投影）。
         *
         *     内置精校模板的置顶与「精校」标注由**前端**完成（复用 OI-34 匹配通路），
         *     后端不掺合模板逻辑。
         */
        VehicleSearchHitOut: {
            /**
             * Record Id
             * @description 记录主键（溯源锚点）
             */
            record_id: number;
            /**
             * Name
             * @description 型号名称（GCAT 原样，检索点选后以此名取参数集）
             */
            name: string;
            /**
             * Variant
             * @description 变体（GCAT 原样；无变体为 null）
             */
            variant: string | null;
            /**
             * Family
             * @description 型号族（GCAT 原样）
             */
            family: string | null;
            /**
             * Country
             * @description 国家/地区（第三层标签解析后的标签值；无标签为 null）
             */
            country: string | null;
            /**
             * Stage Count
             * @description 核心级数（max_stage_no 取整；助推器记 0/−1，GCAT 未给为 null）
             */
            stage_count: number | null;
            /** @description 概览字段可用性摘要 */
            availability: components["schemas"]["AvailabilityOut"];
        };
        /**
         * VehicleSearchResponse
         * @description ``GET /api/catalog/vehicles/search`` 的响应体。
         */
        VehicleSearchResponse: {
            /**
             * Query
             * @description 回显的检索词（原样，未规范化）
             */
            query: string;
            /**
             * Hits
             * @description 候选清单（规范化子串匹配，按「完全匹配 > 前缀 > 子串 > 族/变体」排序，上限 12 条）；检索词为空时为空表
             */
            hits: components["schemas"]["VehicleSearchHitOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_contour_api_geometry_contour_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContourSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_contour_api_geometry_contour__contour_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 母线标识 */
                contour_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_profile_api_geometry_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_geometry_api_geometry_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"] | components["schemas"]["GeometryBuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_api_params_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vehicle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    units_api_params_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitsResponse"];
                };
            };
        };
    };
    read_thresholds_api_params_thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
        };
    };
    write_thresholds_api_params_thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: number | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_api_params_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    match_template_by_name_api_templates_match_get: {
        parameters: {
            query?: {
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_by_id_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_catalog_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialsResponse"];
                };
            };
        };
    };
    engine_catalog_api_catalog_engines_get: {
        parameters: {
            query?: {
                family?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnginesCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_vehicle_records_api_catalog_vehicles_search_get: {
        parameters: {
            query?: {
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vehicle_record_api_catalog_vehicles_record_get: {
        parameters: {
            query: {
                name: string;
                variant?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__key___file__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_api_provenance__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_motor_api_import_motor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotorParseResult"] | components["schemas"]["RocketParseResult"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
