/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/geometry/contour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Contour
         * @description 保存母线：归一化为 canonical JSON 落盘 ``data/contours/<id>.json``。
         *
         *     落盘内容就是 canonical JSON 本体（不含包装元数据），因此
         *     "读取 → 再规范化" 必须与原文件**逐字节相同**——这正是往返一致的判据。
         */
        post: operations["save_contour_api_geometry_contour_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/contour/{contour_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Contour
         * @description 载入母线。文件不存在时返回 404（由 :class:`ArtifactNotFoundError` 映射）。
         */
        get: operations["load_contour_api_geometry_contour__contour_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Profile
         * @description 母线层校验（纯 Python，无内核）：几何自洽 + G1 + 尖点 + 设计意图断言。
         *
         *     响应**同时返回分段采样点**（``sample`` / ``outline``），供前端 2D 剖面与示意通道消费。
         *     这是 ADR-011 的落实方式：端点数值全部来自后端，前端不做任何几何计算。
         */
        post: operations["validate_profile_api_geometry_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geometry/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Geometry
         * @description 构建回转几何：**命中即同步返回**，未命中建异步作业（规格 §9.3）。
         */
        post: operations["build_geometry_api_geometry_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description 跑 §6.3 约束 + §6.5 诊断规则集。
         *
         *     结构错误（缺字段 / 类型不符 / 超出枚举）在进入本函数之前就被 pydantic 拦下，
         *     由 ``main`` 的 ``RequestValidationError`` 处理器翻成同一形状的六字段裁定。
         */
        post: operations["diagnose_api_params_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Units
         * @description 下发 §6.4 的显示单位全表。
         *
         *     这是**只读呈现口径**：不改变存储 / 计算 / 缓存键，故调整显示单位**不得**使
         *     ``artifacts/`` 缓存失效（§9.2）。
         */
        get: operations["units_api_params_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Thresholds
         * @description 返回阈值的生效值与来源。
         *
         *     刻意返回**生效值**而不是"文件里的值"：``PUT`` 之后环境变量仍然覆盖 ``config.toml``，
         *     若界面显示的是文件内容，用户会看到一个"保存了却不生效"的数字而找不到原因。
         */
        get: operations["read_thresholds_api_params_thresholds_get"];
        /**
         * Write Thresholds
         * @description 把补丁写进 ``config.toml``，然后返回**重新读出的**生效状态。
         *
         *     请求体是扁平的 ``{键: 值}``；值为 ``null`` 即**清空该键**（回到「未配置」，
         *     对最小工艺厚度而言就是回到"不判定"）。键必须是 §6.5 已声明的阈值——
         *     多一个键即 422，而不是静默忽略（忽略会让用户以为保存成功）。
         */
        put: operations["write_thresholds_api_params_thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Template
         * @description 返回界面可编辑的示例骨架（§1.7.3 OI-32 的前置）。
         *
         *     ⚠ 这**不是** OI-29 的内置示例模板——模板库须逐条核对公开来源，归 M3。
         *     本端点只提供一份标注为「未经来源核对」的骨架，使参数面板不必自建一份
         *     "看起来像真的"的数字（那会形成与 §13.2 基准表冲突的第二套数字，违反 P1）。
         */
        get: operations["read_template_api_params_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description 查询作业快照。作业不存在时返回 404。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{key}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description 返回产物文件；不在白名单或文件缺失时 404。
         */
        get: operations["get_artifact_api_artifacts__key___file__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provenance/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provenance
         * @description 返回产物清单（provenance.json 内容），供溯源与排障（§9.2 / R-14）。
         */
        get: operations["get_provenance_api_provenance__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针。
         *
         *     M0 验收项（规格 §16）：必须返回版本号，供前端与 CI 核对后端已就绪。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aero
         * @description 气动（简化，§6.1 Aero 层）。
         *
         *     ⚠ 二者均为**工程惯例值，非权威来源**（规格表已标注）；MVP 只做简化模型，
         *     **不做 CFD**（非目标 §1.3）。缺失时按默认值并附 ``warning``。
         */
        Aero: {
            /**
             * Drag Coefficient
             * @description 阻力系数 Cd（工程惯例值，非权威来源；M4 起可用基准火箭反标定）
             */
            drag_coefficient: number;
            /**
             * Reference Area M2
             * @description 参考面积（m²；省略 = 取最大截面积，由后端派生）
             */
            reference_area_m2?: number | null;
        };
        /**
         * ArcSegment
         * @description 球冠段（圆弧）：半径端半径 R 与轴向跨度 H 唯一确定球半径 ρ=(R²+H²)/2H。
         */
        ArcSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "arc";
        };
        /**
         * BuildResponse
         * @description ``POST /api/geometry/build`` 的响应体（§9.3 缓存优先）。
         */
        BuildResponse: {
            /**
             * Cache Hit
             * @description True 表示产物已存在，metrics 直接可用，未创建作业
             */
            cache_hit: boolean;
            /**
             * Key
             * @description 内容寻址缓存键（sha256 十六进制）
             */
            key: string;
            /**
             * Job Id
             * @description 未命中时返回；用 /ws/jobs/{job_id} 订阅进度
             */
            job_id?: string | null;
            /**
             * Metrics
             * @description 命中时的产物指标
             */
            metrics?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CheckResult
         * @description 单项检查结果。
         */
        CheckResult: {
            /**
             * Check
             * @description 检查项名称
             */
            check: string;
            /**
             * Severity
             * @description 裁定：pass / warn / fail / skip
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
            /**
             * Detail
             * @description 人类可读的说明
             */
            detail: string;
            /**
             * Value
             * @description 实测值
             */
            value?: number | null;
            /**
             * Expected
             * @description 期望值
             */
            expected?: number | null;
            /**
             * Relative Error
             * @description 相对误差
             */
            relative_error?: number | null;
        };
        /**
         * ContourResponse
         * @description 母线响应体。``canonical`` 即落盘内容，往返一致的判据（规格 §16.3）。
         */
        ContourResponse: {
            /** Id */
            id: string;
            /**
             * Canonical
             * @description canonical JSON：键序固定、浮点定量、无多余空白
             */
            canonical: string;
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * ContourSaveRequest
         * @description 保存母线的请求体。
         */
        ContourSaveRequest: {
            /**
             * Id
             * @description 母线标识；省略时按 name 派生或随机生成
             */
            id?: string | null;
            /** @description 母线剖面（段链，单位米） */
            profile: components["schemas"]["MeridianProfile"];
        };
        /**
         * DiagnoseResponse
         * @description ``POST /api/params/diagnose`` 的响应体。
         *
         *     ``constraints`` 只可能含**非硬**裁定：硬违反一律走 422，故前端在 200 里看到的
         *     每一条都是"警告级或更轻"，不需要再判一次"是不是该拒绝"。
         */
        DiagnoseResponse: {
            /**
             * Constraints
             * @description §6.3 的四类约束裁定（进入 200 时必为非硬）
             */
            constraints: components["schemas"]["Diagnostic"][];
            /**
             * Diagnostics
             * @description §6.5 规则集产出的诊断（六字段；impact 按 OI-11 归 M4）
             */
            diagnostics: components["schemas"]["Diagnostic"][];
            /**
             * Rules
             * @description §6.5 逐规则账目，含**未判定**的规则与其原因（不得省略）
             */
            rules: components["schemas"]["RuleOutcome"][];
        };
        /**
         * Diagnostic
         * @description 一条字段级裁定（校验错误或方案诊断）。
         */
        Diagnostic: {
            /**
             * Level
             * @description 裁定：hard = 拒绝（硬约束）；warning = 警告
             * @enum {string}
             */
            level: "hard" | "warning";
            /**
             * Code
             * @description 机器可读的判定码，如 PARAMS_FILL_OVERFILL / TWR_TOO_LOW
             */
            code: string;
            /**
             * Field Path
             * @description 字段路径（如 stages[0].engine.mixture_ratio）；整箭层判定用 vehicle 前缀
             */
            field_path: string;
            /**
             * Message
             * @description 面向用户的中文说明：实测值是多少、为什么不行
             */
            message: string;
            /**
             * Suggestion
             * @description 可操作的修复建议（§10.3 要求必填，禁止「未知错误」）
             */
            suggestion: string;
        };
        /**
         * DisplayUnitOut
         * @description 一个量的显示口径（§6.4 表逐行）。
         */
        DisplayUnitOut: {
            /**
             * Quantity
             * @description 量（规格 §6.4 表的「量」列）
             * @enum {string}
             */
            quantity: "force" | "mass" | "length" | "isp" | "velocity" | "pressure" | "temperature" | "density";
            /**
             * Label
             * @description 中文名（规格原文）
             */
            label: string;
            /**
             * Symbol
             * @description 显示单位符号（界面与导出用）
             */
            symbol: string;
            /**
             * Si Symbol
             * @description 内部 SI 符号（存储 / 计算 / 缓存键用）
             */
            si_symbol: string;
            /**
             * Factor
             * @description 换算系数，方向固定 **SI = 显示值 × factor**（方向写反是本表最易犯的错）
             */
            factor: number;
        };
        /**
         * EllipseSegment
         * @description 椭圆弧段：半轴 = (半径端半径 R, 轴向跨度 H)，椭圆心在轴线上。
         */
        EllipseSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ellipse";
        };
        /**
         * Engine
         * @description 发动机（§6.1 Engine 层）。混合比是箱体比例派生的输入（§5.9）。
         */
        Engine: {
            /**
             * Model
             * @description 型号
             */
            model: string;
            /**
             * Propellant Phase
             * @description 推进剂相态（§1.7.3 OI-30）：§6.5 起飞推重比**固体档（1.5）的唯一判据**。默认 liquid —— 实际采用的档位会印在推重比规则的账目里，故非隐式判定
             * @default liquid
             * @enum {string}
             */
            propellant_phase: "liquid" | "solid" | "hybrid";
            /**
             * Cycle
             * @description 循环方式
             * @enum {string}
             */
            cycle: "gas_generator" | "staged_combustion" | "expander" | "pressure_fed";
            /**
             * Chamber Pressure Pa
             * @description 室压
             */
            chamber_pressure_pa: number;
            /**
             * Expansion Ratio
             * @description 喷管膨胀比 ε（面积比）
             */
            expansion_ratio: number;
            /**
             * Efficiency Factor
             * @description 效率因子（c* 或 C_F 效率，1.0 = 理想）
             */
            efficiency_factor: number;
            /**
             * Thrust Sea Level N
             * @description 海平面推力
             */
            thrust_sea_level_n: number;
            /**
             * Thrust Vacuum N
             * @description 真空推力
             */
            thrust_vacuum_n: number;
            /**
             * Isp Sea Level S
             * @description 海平面比冲
             */
            isp_sea_level_s: number;
            /**
             * Isp Vacuum S
             * @description 真空比冲
             */
            isp_vacuum_s: number;
            /**
             * Mixture Ratio
             * @description 混合比 O/F（氧化剂/燃料 质量比）——§5.9 箱体比例派生的唯一输入
             */
            mixture_ratio: number;
        };
        /**
         * ErrorBody
         * @description §10.3 规定的错误响应体。
         */
        ErrorBody: {
            /**
             * Code
             * @description 机器可读的错误码，如 GEOMETRY_G1_DISCONTINUITY
             */
            code: string;
            /**
             * Stage
             * @description 发生阶段：params / meridian / solid / mesh / step / …
             */
            stage: string;
            /**
             * Message
             * @description 面向用户的中文说明
             */
            message: string;
            /**
             * Details
             * @description 结构化上下文
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Suggestion
             * @description 可操作的修复建议（规格 §10.3 要求必填）
             */
            suggestion: string;
        };
        /**
         * Geometry
         * @description 构型（§6.1 Geometry 层），**每级一个**。
         *
         *     整箭外轮廓（§5.2 的母线段列表）挂在 :attr:`Vehicle.profile`：M1 的母线描述的是
         *     **整箭纵剖面**，而共底 / 储箱排列 / 两箱本身是**逐级**属性——若把二者放进一个
         *     ``Geometry``，多级火箭就会出现"一份轮廓对应多个构型"的歧义。
         *
         *     ⚠ 装配关系（§6.1 的示例字段之一）**不在此层**：它随 M5 装配树一并建模（§16）。
         */
        Geometry: {
            /**
             * Common Bulkhead
             * @description 共底设计开关（§5.9 默认关闭）
             * @default false
             */
            common_bulkhead: boolean;
            /**
             * Common Bulkhead Type
             * @description 共底类型（共底开启时必填，由约束引擎判定）
             */
            common_bulkhead_type?: ("insulated_sandwich" | "plain") | null;
            /**
             * Tank Arrangement
             * @description 储箱排列（§5.9 非铁律，用户可配置）
             * @default oxidizer_upper
             * @enum {string}
             */
            tank_arrangement: "oxidizer_upper" | "fuel_upper";
            /**
             * Fins Enabled
             * @description 尾翼 / 稳定面是否启用
             * @default false
             */
            fins_enabled: boolean;
            /** @description 氧化剂箱 */
            oxidizer_tank: components["schemas"]["Tank"];
            /** @description 燃料箱 */
            fuel_tank: components["schemas"]["Tank"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/health`` 的响应体。
         *
         *     作为 OpenAPI schema 的来源，前端 TS 类型由此生成（规格 §18.2：禁止手写重复类型）。
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * JobRecord
         * @description 作业状态快照（跨线程传递的**纯数据**，不含任何几何对象）。
         */
        JobRecord: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** @default queued */
            stage: components["schemas"]["JobStage"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Result Key */
            result_key?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
        };
        /**
         * JobStage
         * @description §9.3 的进度阶段（M1 子集：几何链 ``meridian → solid → mesh → step → done``）。
         * @enum {string}
         */
        JobStage: "queued" | "meridian" | "solid" | "mesh" | "step" | "done";
        /**
         * JobStatus
         * @description §9.3 的作业生命周期状态。
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JointCheck
         * @description 段间接头（G0 由结构保证，此处校 G1）。
         */
        JointCheck: {
            /**
             * Index
             * @description 接头序号：段 index 与 index+1 之间
             */
            index: number;
            /** Z */
            z: number;
            /** Radius */
            radius: number;
            /**
             * Angle Deg
             * @description 两侧切向夹角（度）
             */
            angle_deg: number;
            /**
             * Kind
             * @description g1 = 常规切向；pinch = 轴处反向尖点
             * @enum {string}
             */
            kind: "g1" | "pinch";
            /**
             * Severity
             * @enum {string}
             */
            severity: "pass" | "warn" | "fail" | "skip";
        };
        /**
         * LaunchSite
         * @description 发射场（§6.1 LaunchSite 层）。
         *
         *     纬度是**自转加成与转向损失的唯一输入**（§8.6）：计算中不得另设常量，
         *     否则"改纬度运力不变"这类缺陷会在任何一处悄悄复现。
         */
        LaunchSite: {
            /**
             * Name
             * @description 发射场名称
             */
            name: string;
            /**
             * Latitude Deg
             * @description 纬度（°，北正南负）
             */
            latitude_deg: number;
            /**
             * Altitude M
             * @description 海拔（m，可为负）
             */
            altitude_m: number;
            /**
             * Azimuth Deg
             * @description 发射方位角（°，自正北顺时针；默认值，可被 Mission 覆盖）
             */
            azimuth_deg: number;
        };
        /**
         * LineSegment
         * @description 直线段：柱段（end_radius == 起点半径）或锥段/锥台。
         */
        LineSegment: {
            /**
             * Length
             * @description 轴向跨度（m），正 = 沿 +Z 推进
             */
            length: number;
            /**
             * End Radius
             * @description 本段结束处的半径（m）
             */
            end_radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "line";
        };
        /**
         * LossFactors
         * @description ΔV 损失项系数（§8.6 的损失构成）。
         *
         *     M2 只做**存储与透传**；损失模型 L1 的实算属 M4（§16）。刻意**不设默认值猜测**：
         *     缺省即 0 并在结果中标注为"未计入"，而不是填一个看着合理的经验数（§1.4-4）。
         */
        LossFactors: {
            /**
             * Gravity
             * @description 重力损失（Δv 份额）
             * @default 0
             */
            gravity: number;
            /**
             * Drag
             * @description 气动阻力损失（Δv 份额）
             * @default 0
             */
            drag: number;
            /**
             * Steering
             * @description 转向损失（Δv 份额）
             * @default 0
             */
            steering: number;
            /**
             * Back Pressure
             * @description 背压损失（与「压力/控制余量」同义，§8.8）
             * @default 0
             */
            back_pressure: number;
        };
        /**
         * MeridianProfile
         * @description 母线剖面：底部半径 + 自下而上的段链（规格 §5.2）。
         *
         *     剖面在 (r, z) 平面内描述，回转轴为 Z 轴，单位米。
         *     实体 = 区域 ``{(r, z)}`` 绕 Z 轴回转 360°，其中区域由
         *     ``(0,0) → (base_radius,0) → [段链] → (r_end,z_end) → (0,z_end) → (0,0)`` 围成。
         */
        MeridianProfile: {
            /**
             * Name
             * @description 剖面名称（仅用于展示，不参与几何）
             * @default
             */
            name: string;
            /**
             * Base Radius
             * @description z=0 处的半径（m）
             */
            base_radius: number;
            /**
             * Segments
             * @description 自下而上的段链
             */
            segments: (components["schemas"]["LineSegment"] | components["schemas"]["ArcSegment"] | components["schemas"]["EllipseSegment"])[];
        };
        /**
         * Mission
         * @description 任务与轨道要素（§6.1 Mission 层；轨道要素由 OI-21 补入）。
         */
        Mission: {
            /**
             * Orbit Type
             * @description 目标轨道类型
             * @enum {string}
             */
            orbit_type: "LEO" | "SSO" | "GTO" | "GEO" | "TLI" | "TMI" | "escape" | "custom";
            /**
             * Altitude M
             * @description 圆轨道高度（LEO / SSO / GEO 用）
             */
            altitude_m?: number | null;
            /**
             * Inclination Deg
             * @description 轨道倾角（°）
             */
            inclination_deg?: number | null;
            /**
             * Eccentricity
             * @description 偏心率
             */
            eccentricity?: number | null;
            /**
             * Perigee Altitude M
             * @description 近地点高度（GTO / TLI / TMI 用）
             */
            perigee_altitude_m?: number | null;
            /**
             * Apogee Altitude M
             * @description 远地点高度（GTO / TLI / TMI 用）
             */
            apogee_altitude_m?: number | null;
            /** @description 内联发射场（与 id 二选一） */
            launch_site?: components["schemas"]["LaunchSite"] | null;
            /**
             * Launch Site Id
             * @description 发射场引用（与内联二选一）
             */
            launch_site_id?: string | null;
            /** @description ΔV 损失项系数（§8.6） */
            loss_factors?: components["schemas"]["LossFactors"] | null;
            /**
             * Wind Profile Ref
             * @description 风廓线引用（M6，可空）
             */
            wind_profile_ref?: string | null;
        };
        /**
         * Recovery
         * @description 回收与复用（§6.1 Recovery 层）。
         */
        Recovery: {
            /**
             * Enabled
             * @description 是否回收
             * @default false
             */
            enabled: boolean;
            /**
             * Stage Indices
             * @description 回收的级号
             * @default []
             */
            stage_indices: number[];
            /**
             * Method
             * @description 回收方式
             */
            method?: ("parachute" | "propulsive") | null;
            /**
             * Landing Propellant Margin Fraction
             * @description 着陆推进剂余量（占该级满装量）
             */
            landing_propellant_margin_fraction?: number | null;
            /**
             * System Mass Kg
             * @description 回收系统质量代价
             */
            system_mass_kg?: number | null;
        };
        /**
         * RuleOutcome
         * @description 一条 §6.5 规则的执行账目——**含未判定的部分**。
         */
        RuleOutcome: {
            /**
             * Code
             * @description 规则判定码
             */
            code: string;
            /**
             * Title
             * @description 规则名（§6.5 表「规则」列）
             */
            title: string;
            /**
             * Level
             * @description 该规则违反时的级别（§6.5 表「级别」列）
             * @enum {string}
             */
            level: "hard" | "warning";
            /**
             * Threshold
             * @description 本次实际生效的阈值（含来源标注）
             */
            threshold: string;
            /**
             * Source
             * @description 阈值来源标注（§6.5 强制携带）
             */
            source: string;
            /**
             * Diagnostics
             * @description 本规则产出的裁定；空 = 该规则通过
             * @default []
             */
            diagnostics: components["schemas"]["Diagnostic"][];
            /**
             * Deferred Reason
             * @description **整条规则**未判定的原因（缺输入 / 属后续里程碑）
             */
            deferred_reason?: string | null;
            /**
             * Uncovered
             * @description 规则已判、但**判据分支**未启用的说明（空 = 全覆盖）
             * @default []
             */
            uncovered: string[];
        };
        /**
         * Sequence
         * @description 任务时序（§6.1 Sequence 层）。
         */
        Sequence: {
            /**
             * Events
             * @description 事件列表（按发生顺序）
             */
            events: components["schemas"]["SequenceEvent"][];
        };
        /**
         * SequenceEvent
         * @description 一个任务时序事件（§6.1 Sequence 层）。
         */
        SequenceEvent: {
            /**
             * Event
             * @description 事件类型
             * @enum {string}
             */
            event: "ignition" | "stage_separation" | "fairing_jettison" | "orbit_insertion" | "landing";
            /**
             * Time S
             * @description 相对时刻（s）
             */
            time_s?: number | null;
            /**
             * Trigger
             * @description 触发条件（自由文本，如「燃尽压降 5%」）
             */
            trigger?: string | null;
            /**
             * Stage Index
             * @description 关联级号（可空）
             */
            stage_index?: number | null;
        };
        /**
         * Stage
         * @description 单级（§6.1 Stage 层）。自下而上编号，``index`` 1 = 第一级。
         */
        Stage: {
            /**
             * Index
             * @description 级序号：1 = 第一级（自下而上）
             */
            index: number;
            /**
             * Propellant
             * @description 该级推进剂组合
             * @enum {string}
             */
            propellant: "LOX/RP-1" | "LOX/LH2" | "LOX/CH4" | "N2O4/UDMH";
            /**
             * Diameter M
             * @description 级直径
             */
            diameter_m: number;
            /**
             * Length M
             * @description 级高度（含级间段）
             */
            length_m: number;
            /**
             * Wall Thickness M
             * @description 级壁厚
             */
            wall_thickness_m: number;
            /**
             * Material
             * @description 材料（M3 起由材料库校验）
             */
            material: string;
            /**
             * Structure Coefficient
             * @description 结构系数 σ = m_dry/(m_dry+m_prop)（**存储权威**，§6.1）
             */
            structure_coefficient: number;
            /**
             * Fill Fraction
             * @description 加注比例（上限 1.0，OI-03）
             */
            fill_fraction: number;
            /**
             * Max Fill Mass Kg
             * @description 最大允许加注量（仅超装场景显式启用）
             */
            max_fill_mass_kg?: number | null;
            /**
             * Engine Count
             * @description 发动机台数
             */
            engine_count: number;
            /** @description 该级发动机定义 */
            engine: components["schemas"]["Engine"];
            /**
             * Engine Height M
             * @description 发动机高度（安装基准面 → 喷管出口端面，含喷管）
             */
            engine_height_m: number;
            /**
             * Engine Height Nozzle Excluded M
             * @description 发动机高度（不含喷管）
             */
            engine_height_nozzle_excluded_m?: number | null;
            /**
             * Burn Time S
             * @description 工作时间（s）；省略时由后端按 m_prop/ṁ 派生
             */
            burn_time_s?: number | null;
            /**
             * Interstage Type
             * @description 级间段类型（该级与其**上级之间**的分离段；不是级间舱，§5.9 共性 2）
             * @enum {string}
             */
            interstage_type: "cold_staging" | "hot_staging" | "none";
            /**
             * Isp Vacuum S
             * @description 该级实际使用的真空比冲
             */
            isp_vacuum_s: number;
            /**
             * Isp Sea Level S
             * @description 该级实际使用的海平面比冲
             */
            isp_sea_level_s: number;
            /**
             * Isp Source
             * @description 比冲来源：default = 取自 engine 定义（须一致）；custom = 用户覆写
             * @enum {string}
             */
            isp_source: "default" | "custom";
            /**
             * Recoverable
             * @description 可回收性（回收方案见 Recovery 层）
             * @default false
             */
            recoverable: boolean;
            /** @description 该级构型（共底 / 储箱排列 / 两箱） */
            geometry: components["schemas"]["Geometry"];
        };
        /**
         * Tank
         * @description 贮箱（§6.1 Tank 层）。
         *
         *     ``volume_m3`` / ``nominal_full_mass_kg`` / ``liquid_level_m`` 是**派生量**，
         *     不在此层存储（唯一权威原则）——它们由后端算出并随结果下发。
         */
        Tank: {
            /**
             * Tank Type
             * @description 贮箱类型：非共底 / 共底
             * @enum {string}
             */
            tank_type: "separate" | "common_bulkhead";
            /**
             * Diameter M
             * @description 贮箱直径（省略 = 继承该级直径）
             */
            diameter_m?: number | null;
            /**
             * Length M
             * @description 用户显式给定的箱长（省略 = 由后端按 §5.9 派生）
             */
            length_m?: number | null;
            /**
             * Wall Thickness M
             * @description 壁厚
             */
            wall_thickness_m: number;
            /**
             * Material
             * @description 材料（M3 起由材料库校验）
             */
            material: string;
            /**
             * Fill Fraction
             * @description 加注比例 = 实际加注量 / 满装量；上限 1.0（OI-03，由约束引擎判定）
             */
            fill_fraction: number;
            /**
             * Max Fill Mass Kg
             * @description 最大允许加注量（仅在超装场景显式启用，§6.1 / OI-03）
             */
            max_fill_mass_kg?: number | null;
            /**
             * Feed System
             * @description 输送方式：泵压式 / 挤压式
             * @enum {string}
             */
            feed_system: "pump_fed" | "pressure_fed";
            /**
             * Delivery Pipe Routing
             * @description 输送管走法（§5.9 默认外置沿箭体）
             * @default external
             * @enum {string}
             */
            delivery_pipe_routing: "external" | "internal";
            /**
             * Common Bulkhead Insulation M
             * @description 共底隔热层厚度（共底且 LH₂ 侧必填，§5.9 口径 2）
             */
            common_bulkhead_insulation_m?: number | null;
        };
        /**
         * TemplateResponse
         * @description ``GET /api/params/template`` 的响应体（界面可编辑的起始箭）。
         */
        TemplateResponse: {
            /**
             * Template Id
             * @description 骨架标识
             */
            template_id: string;
            /**
             * Label
             * @description 界面显示名（含「未经来源核对」字样）
             */
            label: string;
            /**
             * Note
             * @description 必须原样呈现的说明；不得改写为更肯定的措辞
             */
            note: string;
            /**
             * Sourced Fields
             * @description 有出处的字段路径 → 出处。**不在本表里的数值一律是占位值**（§1.4-4）；路径口径与 §6.3 / §6.5 的 field_path 逐字一致
             */
            sourced_fields: {
                [key: string]: string;
            };
            /** @description 起始箭本体（结构合法，可直接提交诊断） */
            vehicle: components["schemas"]["Vehicle"];
        };
        /**
         * ThresholdEntry
         * @description 一个阈值的**生效**状态（界面设置项直接消费）。
         */
        ThresholdEntry: {
            /**
             * Key
             * @description 配置键（config.toml 的顶层键名）
             */
            key: string;
            /**
             * Label
             * @description 中文名
             */
            label: string;
            /**
             * Value
             * @description **生效值**；null = 未配置（该判据不判定）
             */
            value: number | null;
            /**
             * Source
             * @description §6.5 强制的来源标注（界面不得自拟措辞）
             */
            source: string;
            /**
             * Origin
             * @description 生效值的来源：环境变量/config.toml/默认值/未配置
             */
            origin: string;
            /**
             * Note
             * @description 生效边界说明
             */
            note: string;
        };
        /**
         * ThresholdsResponse
         * @description ``GET`` / ``PUT /api/params/thresholds`` 的响应体（§1.7.3 OI-31）。
         */
        ThresholdsResponse: {
            /**
             * Config File
             * @description 写入目标：config.toml 的完整路径（§18.4）
             */
            config_file: string;
            /**
             * Thresholds
             * @description 各项的**生效值**与来源；value 为 null 表示「未配置」（该判据不判定）
             */
            thresholds: components["schemas"]["ThresholdEntry"][];
        };
        /**
         * UnitsResponse
         * @description ``GET /api/params/units`` 的响应体（§1.7.3 OI-32）。
         */
        UnitsResponse: {
            /**
             * Units
             * @description §6.4 全表；界面**只按此格式化**，不得在前端再抄一份表或反推系数
             */
            units: components["schemas"]["DisplayUnitOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationReport
         * @description 母线层校验报告（同步接口返回体）。
         */
        ValidationReport: {
            /** Ok */
            ok: boolean;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Joints */
            joints: components["schemas"]["JointCheck"][];
            /**
             * Sample
             * @description 剖面采样点 (r, z)，米
             */
            sample: [
                number,
                number
            ][];
            /**
             * Outline
             * @description 闭合轮廓 (r, z)，米
             */
            outline: [
                number,
                number
            ][];
            /**
             * Envelope
             * @description 解析包络 (2R, 2R, L)，米
             */
            envelope: [
                number,
                number,
                number
            ];
            /**
             * Volume
             * @description 解析体积（m³）
             */
            volume: number;
            /** Surface Area */
            surface_area: number;
            /** Centroid Z */
            centroid_z: number;
            /** Max Radius */
            max_radius: number;
            /** Total Length */
            total_length: number;
        };
        /**
         * Vehicle
         * @description 飞行器总纲（§6.1 Vehicle 层）——前端与后端之间传递的唯一顶层参数对象。
         *
         *     ``total_length_m`` / ``max_diameter_m`` 等**派生量不在此层**：它们由
         *     :mod:`aeroforge.params.dag` 算出并随结果下发（前端零几何计算，ADR-011）。
         */
        Vehicle: {
            /**
             * Schema Version
             * @description 参数 Schema 版本号
             * @default 1
             */
            schema_version: string;
            /**
             * Name
             * @description 火箭名称
             */
            name: string;
            /**
             * Stages
             * @description 自下而上（index 1 = 第一级）
             */
            stages: components["schemas"]["Stage"][];
            /**
             * Payload Mass Kg
             * @description 有效载荷质量
             */
            payload_mass_kg: number;
            /**
             * Fairing Diameter M
             * @description 整流罩直径
             */
            fairing_diameter_m?: number | null;
            /**
             * Material
             * @description 箭体材料（全局默认，可被 Stage 覆盖）
             */
            material: string;
            /**
             * Propellant
             * @description 推进剂组合（全局默认，可被 Stage 覆盖）
             * @enum {string}
             */
            propellant: "LOX/RP-1" | "LOX/LH2" | "LOX/CH4" | "N2O4/UDMH";
            /** @description 气动（缺失时按默认值并附 warning） */
            aero?: components["schemas"]["Aero"] | null;
            /** @description 整箭母线剖面（§5.2 的 2D→3D 入口；M1 已落地） */
            profile?: components["schemas"]["MeridianProfile"] | null;
            /** @description 任务与轨道 */
            mission: components["schemas"]["Mission"];
            /** @description 任务时序 */
            sequence?: components["schemas"]["Sequence"] | null;
            /** @description 回收与复用 */
            recovery?: components["schemas"]["Recovery"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_contour_api_geometry_contour_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContourSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_contour_api_geometry_contour__contour_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 母线标识 */
                contour_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContourResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_profile_api_geometry_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_geometry_api_geometry_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeridianProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_api_params_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vehicle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    units_api_params_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitsResponse"];
                };
            };
        };
    };
    read_thresholds_api_params_thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
        };
    };
    write_thresholds_api_params_thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: number | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_api_params_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__key___file__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_api_provenance__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 内容寻址缓存键 */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
